### ISSUE TITLE
Shard count doesn't respect the closed and special selection

### ISSUE THREAD

**Issue by fhopf** [lmenezes/cerebro#10]
By default the special indices (starting with a dot) are not displayed in the cluster view. The count of unassigned shards still counts them which can be confusing.

**Comment by lmenezes** [comment]
@fhopf fair point, even though I'm not really sure what to do here.

Hiding the unassigned shard(or initializing, relocating...) seems to be removing useful functionality which also lets you know things might not be as you expect.

Displaying this, and at the same time not displaying the index which has the unassigned/initializing/relocating shards, also seems kind of odd.

Do you have any suggestion?
