### ISSUE TITLE
Store rest queries?

### ISSUE THREAD

**Issue by webedem** [lmenezes/cerebro#100]
It would be great if there was a way to store any queries run through the REST page, for future usage. Is it possible to do so ?

**Comment by lmenezes** [comment]
This is already done on the latest version. By default, it will keep the last 50 requests for each user(if you use auth, otherwise just the last 50 in general). 

You can override this to any other value though:
```
# Rest request history max size per user
rest.history.size = 50 // defaults to 50 if not specified
```
