### ISSUE TITLE
Cerebro 0.6.1 fails to start on Windows due to long classpath

### ISSUE THREAD

**Issue by davestephens** [lmenezes/cerebro#102]
If cerebro is installed anywhere with anything more than a short path, it fails to start due to the long `APP_CLASSPATH` variable in bin\cerebro.bat.

Eg, if I unpack Cerebro in c:\cerebro\packages\cerebro-0.6.1 and run c:\cerebro\packages\cerebro-0.6.1\bin\cerebro.bat, I get:

```
The input line is too long.
The syntax of the command is incorrect.
```

If I move the Cerebro-0.6.1 folder to the root of C:, it launches fine. 

It seems to be related to the expansion of `%APP_LIB_DIR%` within the `%APP_CLASSPATH%` variable in the launch script. 

Perhaps this could be changed to a relative path to shorten the length of the string?

**Comment by PeterMen** [comment]
Before your team release your code , there is no test??????????
so fuck !

**Comment by davestephens** [comment]
Thanks for fixing (@Tonyko) and merging (@lmenezes) so quickly guys, appreciate it.

**Comment by davestephens** [comment]
@PeterMen Thanks for the helpful contribution.
