### ISSUE TITLE
Cerebro 0.6.1 snapshot listing timeout over 60 seconds

### ISSUE THREAD

**Issue by nokiomanz** [lmenezes/cerebro#103]
Hi, 

I was using kopf under my 2.x elasticsearch cluster and was listing my snapshot from my s3 directory with no problem. I always have the last year worth of daily snapshot in S3.

Upgrading my cluster to 5.x. I installed Cerebro 0.6.1. Everything work perfectly apart from listing my snapshot. It give an error "Error connecting to the server".

curl -XGET '127.0.0.1:9200/_snapshot/dp-prod-backup/_all?pretty' i can see that it takes around 1 minutes 10 seconds with my setup.

In Cerebro I see that I get the error at 60 second everytime. Which make be believe that there is a timeout of 1 minutes.

Is there a way to change that?

**Comment by nokiomanz** [comment]
Nevermind. They say that a night of sleep helps.... In this case a whole weekend. This morning I though to myself, why would there be a timeout of 60 seconds. Then I remembered that I am proxying through apache

I added a "timeout 90" to my config and now all work perfectly fine!

Sorry for the trouble.

**Comment by lmenezes** [comment]
haha, thank you for following up on this. 

I haven't invested much time on it, but I had already discarded all points where a 60s timeout could be occurring, so I was a bit puzzled and wondering where to look next :)

**Comment by nokiomanz** [comment]
Thank you for your time!
Have a great day!
