### ISSUE TITLE
 play.api.UnexpectedException: JsResultException

### ISSUE THREAD

**Issue by eperry** [lmenezes/cerebro#104]
I just downloaded .0.6.1  
openjdk version "1.8.0_121"

And getting this error.  Not sure how to address this ieeu

> 2017-03-19 13:02:36,447 - [ERROR] - from application in ForkJoinPool-2-worker-15
> 
> 
> ! @73d3e75mo - Internal server error, for (POST) [/overview] ->
> 
> play.api.UnexpectedException: Unexpected exception[JsResultException: JsResultException(errors:List((,List(ValidationError(List('jUs3FZC7QD21038gQKx9zg' is undefined on object: {"v9fEyAu_QFeL9-x-gwg8zw":{"timestamp":1489942956391,"name":"hd1melk25lx-es-data","transport_address":"10.32.42.205:9315","host":"hd1melk25lx","ip":"10.32.42.205:9315","roles":["data","ingest"],"attributes":{"rack":"hbcglobal"},"os":{"timestamp":1489942956008,"cpu":{"percent":7,"load_average":{"1m":0.8,"5m":1.04,"15m":1.06}},"mem":{"total":"94.4gb","total_in_bytes":101429366784,"free":"24gb","free_in_bytes":25806741504,"used":"70.4gb","used_in_bytes":75622625280,"free_percent":25,"used_percent":75},"swap":{"total":"3.9gb","total_in_bytes":4294963200,"free":"3.9gb","free_in_bytes":4283781120,"used":"10.6mb","used_in_bytes":11182080}},"process":{"timestamp":1489942956008,"open_file_descriptors":885,"max_file_descriptors":842398,"cpu":{"percent":3,"total":"1.4d","total_in_millis":126908420},"mem":{"total_virtual":"39.2gb","total_virtual_in_bytes":42132324352}},"jvm":{"timestamp":1489942956010,"uptime":"3d","uptime_in_millis":262454831,"mem":{"heap_used":"943.9mb","heap_used_in_bytes":989764048,"heap_used_percent":47,"heap_committed":"1.9gb","heap_committed_in_bytes":2075918336,"heap_max":"1.9gb","heap_max_in_bytes":2075918336,"non_heap_used":"125.7mb","non_heap_used_in_bytes":131838808,"non_heap_committed":"132.2mb","non_heap_committed_in_bytes":138706944,"pools":{"young":{"used":"11.9mb","used_in_bytes":12557816,"max":"546.1mb","max_in_bytes":572653568,"peak_used":"546.1mb","peak_used_in_bytes":572653568,"peak_max":"546.1mb","peak_max_in_bytes":572653568},"survivor":{"used":"31.8mb","used_in_bytes":33437664,"max":"68.2mb","max_in_bytes":71565312,"peak_used":"68.2mb","peak_used_in_bytes":71565312,"peak_max":"68.2mb","peak_max_in_bytes":71565312},"old":{"used":"900mb","used_in_bytes":943768568,"max":"1.3gb","max_in_bytes":1431699456,"peak_used":"1gb","peak_used_in_bytes":1119490880,"peak_max":"1.3gb","peak_max_in_bytes":1431699456}}},"threads":{"count":206,"peak_count":240},"gc":{"collectors":{"young":{"collection_count":82402,"collection_time":"11.5m","collection_time_in_millis":693512},"old":{"collection_count":150,"collection_time":"8.1s","collection_time_in_millis":8105}}},"buffer_pools":{"direct":{"count":179,"used":"368.6mb","used_in_bytes":386555933,"total_capacity":"368.6mb","total_capacity_in_bytes":386555932},"mapped":{"count":3383,"used":"27.2gb","used_in_bytes":29240178606,"total_capacity":"27.2gb","total_capacity_in_bytes":29240178606}},"classes":{"current_loaded_count":11215,"total_loaded_count":11431,"total_unloaded_count":216}},"fs":{"timestamp":1489942956011,"total":{"total":"1.5tb","total_in_bytes":1690493976576,"free":"1.5tb","free_in_bytes":1652740415488,"available":"1.4tb","available_in_bytes":1566841069568,"spins":"true"},"data":[{"path":"/es-data1/hbc/nodes/0","mount":"/es-data1 (/dev/emcpowerf)","type":"ext4","total":"393.5gb","total_in_bytes":422623494144,"free":"386.3gb","free_in_bytes":414885027840,"available":"366.3gb","available_in_bytes":393410191360,"spins":"true"},{"path":"/es-data2/hbc/nodes/0","mount":"/es-data2 (/dev/emcpowerg)","type":"ext4","total":"393.5gb","total_in_bytes":422623494144,"free":"386.3gb","free_in_bytes":414854672384,"available":"366.3gb","available_in_bytes":393379835904,"spins":"true"},{"path":"/es-data3/hbc/nodes/0","mount":"/es-data3 (/dev/emcpowerh)","type":"ext4","total":"393.5gb","total_in_bytes":422623494144,"free":"380.2gb","free_in_bytes":408303177728,"available":"360.2gb","available_in_bytes":386828341248,"spins":"true"},{"path":"/es-data4/hbc/nodes/0","mount":"/es-data4 (/dev/emcpoweri)","type":"ext4","total":"393.5gb","total_in_bytes":422623494144,"free":"386.2gb","free_in_bytes":414697537536,"available":"366.2gb","available_in_bytes":393222701056,"spins":"true"}],"io_stats":{"devices":[{"device_name":"emcpowerf","operations":7635860,"read_operations":55,"write_operations":7635805,"read_kilobytes":220,"write_kilobytes":191195452},{"device_name":"emcpowerg","operations":6603773,"read_operations":13,"write_operations":6603760,"read_kilobytes":52,"write_kilobytes":165984872},{"device_name":"emcpowerh","operations":7142031,"read_operations":14,"write_operations":7142017,"read_kilobytes":56,"write_kilobytes":163407796},{"device_name":"emcpoweri","operations":7184595,"read_operations":15,"write_operations":7184580,"read_kilobytes":60,"write_kilobytes":173885392}],"total":{"operations":28566259,"read_operations":97,"write_operations":28566162,"read_kilobytes":388,"write_kilobytes":694473512}}}},"fQLXlScmSt2CaZP7lrNzNw":{"timestamp":1489942956391,"name":"hd1melk26lx-es-data","transport_address":"10.32.42.206:9315","host":"hd1melk26lx","ip":"10.32.42.206:9315","roles":["data","ingest"],"attributes":{"rack":"hbcglobal"},"os":{"timestamp":1489942956008,"cpu":{"percent":8,"load_average":{"1m":1.13,"5m":1.47,"15m":1.57}},"mem":{"total":"94.4gb","total_in_bytes":101429047296,"free":"14.4gb","free_in_bytes":15549747200,"used":"79.9gb","used_in_bytes":85879300096,"free_percent":15,"used_percent":85},"swap":{"total":"3.9gb","total_in_bytes":4294963200,"free":"3.9gb","free_in_bytes":4283346944,"used":"11mb","used_in_bytes":11616256}},"process":{"timestamp":1489942956009,"open_file_descriptors":880,"max_file_descriptors":842398,"cpu":{"percent":3,"total":"1.8d","total_in_millis":157392470},"mem":{"total_virtual":"39.2gb","total_virtual_in_bytes":42158604288}},"jvm":{"timestamp":1489942956010,"uptime":"3d","uptime_in_millis":262454684,"mem":{"heap_used":"1.3gb","heap_used_in_bytes":1483244480,"heap_used_percent":71,"heap_committed":"1.9gb","heap_committed_in_bytes":2075918336,"heap_max":"1.9gb","heap_max_in_bytes":2075918336,"non_heap_used":"126.5mb","non_heap_used_in_bytes":132695592,"non_heap_committed":"132.6mb","non_heap_committed_in_bytes":139096064,"pools":{"young":{"used":"409mb","used_in_bytes":428902616,"max":"546.1mb","max_in_bytes":572653568,"peak_used":"546.1mb","peak_used_in_bytes":572653568,"peak_max":"546.1mb","peak_max_in_bytes":572653568},"survivor":{"used":"31.8mb","used_in_bytes":33432416,"max":"68.2mb","max_in_bytes":71565312,"peak_used":"68.2mb","peak_used_in_bytes":71565312,"peak_max":"68.2mb","peak_max_in_bytes":71565312},"old":{"used":"973.6mb","used_in_bytes":1020913640,"max":"1.3gb","max_in_bytes":1431699456,"peak_used":"1.1gb","peak_used_in_bytes":1186022288,"peak_max":"1.3gb","peak_max_in_bytes":1431699456}}},"threads":{"count":217,"peak_count":252},"gc":{"collectors":{"young":{"collection_count":77433,"collection_time":"14.2m","collection_time_in_millis":857172},"old":{"collection_count":134,"collection_time":"9.1s","collection_time_in_millis":9139}}},"buffer_pools":{"direct":{"count":197,"used":"368.8mb","used_in_bytes":386764669,"total_capacity":"368.8mb","total_capacity_in_bytes":386764668},"mapped":{"count":3387,"used":"27.2gb","used_in_bytes":29253891788,"total_capacity":"27.2gb","total_capacity_in_bytes":29253891788}},"classes":{"current_loaded_count":11255,"total_loaded_count":11492,"total_unloaded_count":237}},"fs":{"timestamp":1489942956012,"total":{"total":"1.5tb","total_in_bytes":1690493976576,"free":"1.5tb","free_in_bytes":1652603297792,"available":"1.4tb","available_in_bytes":1566703951872,"spins":"true"},"data":[{"path":"/es-data1/hbc/nodes/0","mount":"/es-data1 (/dev/emcpowerf)","type":"ext4","total":"393.5gb","total_in_bytes":422623494144,"free":"386.3gb","free_in_bytes":414851489792,"available":"366.3gb","available_in_bytes":393376653312,"spins":"true"},{"path":"/es-data2/hbc/nodes/0","mount":"/es-data2 (/dev/emcpowerg)","type":"ext4","total":"393.5gb","total_in_bytes":422623494144,"free":"380.2gb","free_in_bytes":408276221952,"available":"360.2gb","available_in_bytes":386801385472,"spins":"true"},{"path":"/es-data3/hbc/nodes/0","mount":"/es-data3 (/dev/emcpowerh)","type":"ext4","total":"393.5gb","total_in_bytes":422623494144,"free":"386.2gb","free_in_bytes":414688391168,"available":"366.2gb","available_in_bytes":393213554688,"spins":"true"},{"path":"/es-data4/hbc/nodes/0","mount":"/es-data4 (/dev/emcpoweri)","type":"ext4","total":"393.5gb","total_in_bytes":422623494144,"free":"386.3gb","free_in_bytes":414787194880,"available":"366.3gb","available_in_bytes":393312358400,"spins":"true"}],"io_stats":{"devices":[{"device_name":"emcpowerf","operations":7430946,"read_operations":21,"write_operations":7430925,"read_kilobytes":84,"write_kilobytes":186966244},{"device_name":"emcpowerg","operations":7038061,"read_operations":114,"write_operations":7037947,"read_kilobytes":456,"write_kilobytes":160082720},{"device_name":"emcpowerh","operations":5917621,"read_operations":21,"write_operations":5917600,"read_kilobytes":84,"write_kilobytes":139753800},{"device_name":"emcpoweri","operations":7449597,"read_operations":17,"write_operations":7449580,"read_kilobytes":68,"write_kilobytes":176733596}],"total":{"operations":27836225,"read_operations":173,"write_operations":27836052,"read_kilobytes":692,"write_kilobytes":663536360}}}}}),WrappedArray())))))]
>         at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
>         at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
>         at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
>         at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
>         at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
>         at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
>         at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
>         at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
>         at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
>         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
>         at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
>         at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
>         at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
>         at scala.concurrent.Promise$class.complete(Promise.scala:55)
>         at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
>         at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
>         at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
>         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
>         at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>

**Comment by eperry** [comment]
Oh, I am running elasticsearch 5.1.2

**Comment by eperry** [comment]
Closing issue, I upgraded to Elastic 5.2.2.

**Comment by kiss01** [comment]
is there someway without  es upgrading?
