### ISSUE TITLE
Cerebro - Connection refused

### ISSUE THREAD

**Issue by hkhail** [lmenezes/cerebro#105]
Hello,

I am securizing Elasticsearch with the plugin "**Readonlyrest**". I specified a user/password for Cerebro.
In application.conf, I defined this user/password to connect to ES

`hosts = [
  {
    host = "http://localhost:9200"
    name = "Secured Cluster"
    auth = {
      username = "cerebro"
      password = "cerebro"
    }
  }
]`

However, I get the following error : 

> Caused by: java.net.ConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:9200

Are the values of the attributes "username" and "password" sent to connect to Elasticsearch ?

H.

**Comment by lmenezes** [comment]
yes, username/password are sent to connect to ES.

Is elastic search running on the same server as cerebro? Also, do you have a special value defined for network.host/bind_host?

**Comment by hkhail** [comment]
I checked the configuration of the ReadOnlyRest plugin. It is working now.
Thanks
