### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by hkhail** [lmenezes/cerebro#110]
Hello,

In the previous version, these two lines were the application.conf file

- play.modules.enabled += "controllers.auth.Module"
- play.modules.enabled += "elastic.ElasticModule"

However, in the last version 0.6.3, these lines are not in the **application.conf** or **reference.conf** files.

Is it not more useful ?

Regards
H.

**Comment by lmenezes** [comment]
@hkhail no, this lines are no longer necessary(they would actually prevent the app from working now) :)
