### ISSUE TITLE
Big memory consumption

### ISSUE THREAD

**Issue by ineu** [lmenezes/cerebro#112]
I'm running cerebro 0.6.1. It's mostly idle, quite rarely used. It's running for a week now:
```
   Active: active (running) since Fri 2017-03-17 07:54:05 UTC; 1 weeks 0 days ago
```
and I've just noticed that the memory consumption is pretty big:
```
# ps aux | head -1; ps uax| grep [c]erebr
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     25787  0.4  7.0 12310640 2311840 ?    Ssl  Mar17  31:22 java -Duser.dir=/opt/cerebro-0.6.1 -Dpidfile.path=/dev/null ....
```
so it's 2.3GB RSS

I'm running cerebro with a very simple systemd unit, almost no options:
```
# /etc/systemd/system/cerebro.service
[Unit]
After = network.target

[Service]
ExecStart = /opt/cerebro/bin/cerebro -Dpidfile.path=/dev/null 

[Install]
WantedBy=multi-user.target

```

Is there some configuration I can tune to limit the amount of memory cerebro uses? I can set the memory limit via systemd, but it will trigger OOM killer invocations, so I'd prefer less intrusive way.
Thank you.

**Comment by dylanmei** [comment]
I use `Environment="ACTIVATOR_OPTS=-J-Xmx1024m"`

**Comment by lmenezes** [comment]
@ineu is this what you meant? You can reduce the max heap as much as you want(although I'm sure there will be a minimum). But the app itself should not really need much memory

**Comment by ineu** [comment]
Probably it is, I'll try. I was suprised to see it using 2GB RAM. Thanks for the tip

**Comment by lmenezes** [comment]
@ineu great :)

**Comment by ineu** [comment]
Unfortunately that doesn't help:
```
[root@svc-es5 ~]# systemctl cat cerebro
# /etc/systemd/system/cerebro.service
[Unit]
After = network.target

[Service]
ExecStart = /opt/cerebro/bin/cerebro -Dpidfile.path=/dev/null 
Environment="ACTIVATOR_OPTS=-J-Xmx256m"

[Install]
```
```
[root@svc-es5 ~]# cat /proc/21373/environ | tr '\0' '\n'
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
PWD=/
LANG=en_US.UTF-8
ACTIVATOR_OPTS=-J-Xmx256m
SHLVL=0
```

```
[root@svc-es5 ~]# ps aux | head -1; ps aux| grep [c]erebr
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     21373  0.0  4.4 11877628 1474384 ?    Ssl  Apr01  39:38 java -Duser.dir=/opt/cerebro-0.6.1 -Dpidfile.path=/dev/null -cp /opt/cerebro-0.6.1/lib/../conf/:/opt/cerebro-0.6.1/lib/cerebro.cerebro-0.6.1-sans-externalized.jar:/opt/cerebro-0.6.1/lib/org.scala-lang.scala-library-2.11.8.jar:/opt/cerebro-0.6.1/lib/com.typesafe.play.twirl-api_2.11-1.1.1.jar:/opt/cerebro-0.6.1/lib/org.apache.commons.commons-lang3- .........
```

**Comment by FestivalBobcats** [comment]
I seem to be having a similar issue inside a Docker container (ludekvesely/docker-elastic-cerebro). It's consuming around 5gb of RAM.

Setting `ACTIVATOR_OPTS=-J-Xmx256m` didn't seem to resolve the issue.

**Comment by FestivalBobcats** [comment]
I've also now tried `JAVA_OPTS=-Xmx256m` (as well as several other variants), and can see the options are being passed to the process.

However, it doesn't seem as though Cerebro will _ever_ consume less than ~400mb of RAM, even just idling. When clicking around in the UI, I can see the memory usage jump slightly higher. And, as mentioned before, there was an extreme case where we saw it using 5gb of RAM.

We're running this as the primary monitoring tool for all 5.x ES clusters at qbox.io, and we just recently noticed it's causing a major uptick in infrastructure expense due to the RAM Cerebro is consuming, so we're having to explore other options right now.

Would love some input if anyone has any idea what is going on.

**Comment by lmenezes** [comment]
Have any of you tried just running the app like:
```
./bin/cerebro -J-Xms64M -J-Xmx64m -J-server
```

I have just tried that and it works as expected.

**Comment by ineu** [comment]
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      6970  0.0  0.5 3704628 189716 ?      Ssl  06:52   0:10 java -Duser.dir=/opt/cerebro-0.6.1 -Dpidfile.path=/dev/null -Xms64M -Xmx64m -server 
```
I'll upgrade to 0.6.5 and check how it behaves there

**Comment by lmenezes** [comment]
ok, just noticed you guys are talking about the virtual memory used, not the heap space.

For that there is no setting to limit the memory usage, but looking at your numbers(and also the instance I have running) its not normal that its taking so much. 

I'm reopening this and will investigate where the usage comes from.

**Comment by daniilyar** [comment]
@lmenezes , first of all, thank you for the awesome tool you wrote! 

As for memory usage, anyone who run Java inside the container should know that before update 1.8.u131 Java was not aware of (cgroup) container memory limit. So, by default, Java may set Xmx, higher than container limit. Hence Java can (and will) try to use more than container limit and OOMKiller will happily kill it.

Here are the optimal Java options for Cerebro which we ended up in our production setup:
```
-J-Xms150m -J-Xmx150m -J-Xss256k -J-XX:MaxMetaspaceSize=100m -J-XX:MaxMetaspaceExpansion=15m -J-XX:CompressedClassSpaceSize=10m -J-XX:ReservedCodeCacheSize=15m -J-XX:+HeapDumpOnOutOfMemoryError -J-XX:+UseCompressedOops
```

With thee options, the overall 'RES' memory usage of cerebro is always under 300Mb, so with these options you may set e.g. 350Mb as container memory limit.

**Comment by lmenezes** [comment]
is anyone still having this issue?

**Comment by ineu** [comment]
It works fine for me in version 0.6.7
