### ISSUE TITLE
Read 'hosts' list from command line

### ISSUE THREAD

**Issue by ayashjorden** [lmenezes/cerebro#120]
Hi,
I'm running Cerebro in a container using [yannart/cerebro](https://hub.docker.com/r/yannart/cerebro/).

How can I pass the list of hosts so users won't need to type it when connecting to cerebro?

BTW, Cerebro is my favorite ES admin console.

Thank you,
Jorden

**Comment by dylanmei** [comment]
This works for me: `cerebro -Dhosts.0.host=http://server1:9200 -Dhosts.1.host=http://server2:9200`

**Comment by ayashjorden** [comment]
Is this documented somewhere? Looked in Play docs, Akka...

**Comment by dylanmei** [comment]
I believe it's part of the underlying configuration framework. More about it in this article here: http://blog.michaelhamrah.com/2014/02/leveraging-typesafes-config-library-across-environments

But no, I can't find an explicit reference to it.

**Comment by ayashjorden** [comment]
Thank you!
