### ISSUE TITLE
Disable SSL verification

### ISSUE THREAD

**Issue by arossert** [lmenezes/cerebro#127]
Is there an option to disable certificate and/or hostname verification when using SSL?

This is the error message:
`Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching myelastic.com found`

**Comment by arossert** [comment]
I have found the solution, need to put this in configuration to disable SSL verification.

```
play.ws.ssl.loose.acceptAnyCertificate = true
```

**Comment by gittygoo** [comment]
can this be passed over a docker environment var or just by volume-mounting the application.conf?

**Comment by kiddom-kq** [comment]
@gittygoo no, but you can pass that in as a CLI argument the same way you would the port:

```shell
❯ docker run lmenezes/cerebro -Dhttp.port=9012
<...>
[info] play.api.Play - Application started (Prod) (no global state)
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9012
```

becomes

```
docker run lmenezes/cerebro -Dplay.ws.ssl.loose.acceptAnyCertificate=true
```

Or add the `-D....` to your `entrypoint:` block for docker-compose
