### ISSUE TITLE
nodes view not working on an Elasticsearch 5.1 cluster

### ISSUE THREAD

**Issue by my-digital-decay** [lmenezes/cerebro#128]
Attempting to view the **nodes** tab in cerebro on an ES 5.1 cluster results in the following error:

```
play.api.UnexpectedException: Unexpected exception[JsResultException: JsResultException(errors:List((,List(ValidationError(List('version' is undefined on object: {"pid":4536,"start_time":"2017-04-12T20:28:23.429Z","start_time_in_millis":1492028903429,"mem":{"heap_init":"5gb","heap_init_in_bytes":5368709120,"heap_max":"4.9gb","heap_max_in_bytes":5351276544,"non_heap_init":"2.4mb","non_heap_init_in_bytes":2555904,"non_heap_max":"0b","non_heap_max_in_bytes":0,"direct_max":"4.9gb","direct_max_in_bytes":5351276544},"using_compressed_ordinary_object_pointers":"true"}),WrappedArray())))))]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
```

It appears that the **version** field is no longer returned in the **jvm** block when calling `_nodes/_all`.

**Comment by lmenezes** [comment]
@my-digital-decay I have just tested this with ES 5.0, 5.1.1 and 5.3.0, and with all of them this worked fine.
I also checked _nodes/_all, and they all also returned the jvm version information.

Is there anything unusual on your setup? OS? JVM?

**Comment by my-digital-decay** [comment]
@lmenezes Yeah sorry, I failed to mention that this is a cluster using the AWS Elasticsearch Service. Amazon must have modified the API so it doesn't report the same information in their managed clusters. I assumed it was just a version related issue.

I've been using **kopf** on a custom managed cluster and love it. So far **cerebro** seems to work just as well with the AWS managed cluster, except for this nodes view issue. Would love to get this working on the AWS managed cluster. Let me know if there's anything I can do to help.
