### ISSUE TITLE
Please make the port configurable

### ISSUE THREAD

**Issue by alexandrul** [lmenezes/cerebro#13]
SonarQube uses 9000 too (it has multiple types of runners, all of which should be configured to a different port).

**Comment by lmenezes** [comment]
hey :)

you should be able to run it as:
```
./bin/cerebro -Dhttp.port=9001
```
as just set the port you want. Let me know if this works fine.

**Comment by alexandrul** [comment]
Hi, indeed it works. However, setting the port in the config file would make it easier to share it to other coworkers.

**Comment by burzum** [comment]
@Imenezes how do I set the port in the cerebro.bat file...?
