### ISSUE TITLE
Support for bulk queries in the rest tab

### ISSUE THREAD

**Issue by consulthys** [lmenezes/cerebro#130]
It would be extremely useful if the `rest` tab would support [bulk format](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) as it was the case in the kopf plugin. Right now, it only supports valid JSON and I've not found a way to get around that.

It should be possible to send a bulk query like this one:

```
POST /test/test/_bulk
{"index":{}}
{"test": "test2"}
{"index":{}}
{"test": "test3"}
{"index":{}}
{"test": "test4"}
```

But right now this produces the following Javascript error:
```
lib.js:119 SyntaxError: Unexpected token { in JSON at position 13
    at JSON.parse (<anonymous>)
    at AceEditor.getValue (app.js:1662)
    at m.$scope.execute (app.js:1215)
    at fn (eval at compile (lib.js:228), <anonymous>:4:212)
    at b (lib.js:127)
    at e (lib.js:270)
    at m.$eval (lib.js:146)
    at m.$apply (lib.js:146)
    at HTMLButtonElement.<anonymous> (lib.js:270)
    at HTMLButtonElement.dispatch (lib.js:3)
```

**Comment by lmenezes** [comment]
sure thing.

The ideal solution would be to make the ace editor recognise  both json and also the multiline json supported by ES. But this might be a lot of work for the little time I have available currently, so I will just go ahead with "ignoring" the malformed json(which just means, you will see errors on the editor, and no of course, no validation of the payload).

**Comment by consulthys** [comment]
I understand. How did you make it work in the `kopf` plugin?

**Comment by lmenezes** [comment]
@consulthys this is already fixed, I just havent found the time to publish a release. Will try to a new release by the end of the day :)
