### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by arossert** [lmenezes/cerebro#133]
I'm getting this error while running this query:
```
{
  "size": 1000,
  "query": {
    "filtered": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "records_len": {
                  "gte": 130
                }
              }
            }
          ]
        }
      }
    }
  }
}
```

also, there is no indication of the error in the screen, only in the browser console.

This is the full backtrace:
```
lib.js:119 RangeError: Invalid string length
at Array.join (native)
at h (http://localhost:9000/js/lib.js:395:743)
at f (http://localhost:9000/js/lib.js:395:490)
at m (http://localhost:9000/js/lib.js:395:1083)
at http://localhost:9000/js/lib.js:395:578
at Array.map (native)
at g (http://localhost:9000/js/lib.js:395:555)
at f (http://localhost:9000/js/lib.js:395:499)
at m (http://localhost:9000/js/lib.js:395:1083)
at http://localhost:9000/js/lib.js:395:578
```

**Comment by lmenezes** [comment]
hum, this is very odd. which browser are you using?

**Comment by arossert** [comment]
I used chrome & firefox.
If I understand correctly this happened when the return value from the server was a very long string (the documents are pretty big).

**Comment by lmenezes** [comment]
@arossert yep, i looked around and it seems you are right. and unfortunately also not much I can do about it(perhaps I could catch the error and warn about it, but I doubt this adds much value). sorry :)
