### ISSUE TITLE
unsupported java version

### ISSUE THREAD

**Issue by petrmalkov** [lmenezes/cerebro#136]
centos7
        #java -version
java version "1.7.0_131"

cerebro-0.6.5.tgz
        #bin/cerebro
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0

I also tried to install from java site latest jdk-8u131-linux-x64.rpm

How to fix or how to recompile (detailed if possible) with existing java ?

**Comment by lmenezes** [comment]
hey @petrmalkov 
sorry but cerebro needs at least java 8, because some of its dependencies already require it.

**Comment by petrmalkov** [comment]
so where from to get it for centos 7?

**Comment by petrmalkov** [comment]
answer:

#cd /opt/
#wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
#tar xzf jdk-8u131-linux-x64.tar.gz
#cd /opt/jdk1.8.0_131/
#alternatives --install /usr/bin/java java /opt/jdk1.8.0_131/bin/java 2
#alternatives --config java
(choose numbet of /opt/...)
