### ISSUE TITLE
feature: Add Filter for "initializing/relocating shards"

### ISSUE THREAD

**Issue by danielmotaleite** [lmenezes/cerebro#138]
I have 8k shards and when the cluster is re-balancing , i have a very hard time finding in what shards Elasticsearch is working on.

Just like you have the "show only unassigned shards", it should also show "show only initializing/relocating shards", so we can easily track those changes

**Comment by supernomad** [comment]
I am pretty sure this filter is failing due to this line: https://github.com/lmenezes/cerebro/blob/master/app/models/overview/Index.scala#L46 its looking for `state` in the top level shard object returned from elasticsearch, but its actually exists at `shard -> routing -> state`

**Comment by danielmotaleite** [comment]
@supernomad what i'm requesting is being able to see "all shards", "unassigned shards"  AND "currently initializing/relocating shards" ... what you are reporting looks like the "unassigned shards" is not changing the view from the "all shards"... is this correct?

**Comment by lmenezes** [comment]
@danielmotaleite There was never a "show only unassigned shards". There is a "show only affected indices", which sits below of the text that says either XXX unassigned shards, or XX relocating shards.

I did think about having separate filters for relocating/initializing, but decided that this was complicating things too much on the ui, for likely little benefit: unassigned shards will eventually become initializing, and if there are no unassigned, even though the filter would also display indices with unassigned shards, it will make no difference.

**Comment by danielmotaleite** [comment]
@lmenezes sorry, you are right, the text is "show only affected indices", but the effect is the same, i can't see what shards is elasticsearch working on at that time.

My problem is that with 8k shards, when i reboot one server in the cluster, i have thousands of unassigned shards, spreading between hundred of pages and withless than 10 being relocated.

I would like to see those relocating 10 shards names, but right now is almost impossible to find then.

My feature request was changing that link to maybe a drop down list with "all, unassigned, relocating".
For me, relocating everything after a server reboot takes maybe 6 hours, so having some idea what shards is elasticsearch working on it is helpful to report to the users.

If you do not like a drop down list, simply do the first click on the link show the unassigned+relocating, the next one only relocating, the next again showing again everything
