### ISSUE TITLE
Change relocation color box to a more visible one

### ISSUE THREAD

**Issue by danielmotaleite** [lmenezes/cerebro#139]
i liked more the old kopf "color filled" shards, as it was easier to see the different types (primary, replica, relocating), specially when we have many... the worst problem is the replica vs relocating blocks, they look very similar and hard to detect. So please put the relocating color a more visible color, like yellow, to make it easier to compare it against the "replica green box"

**Comment by lmenezes** [comment]
@danielmotaleite hey daniel. I'm actually happy with the way the shard maps looks currently(and also think its much easier to see the difference between primary/replica as it is).

so, at least for now, i will leave this unchanged :)

**Comment by danielmotaleite** [comment]
i understand , it's a matter of different taste...  and you win, it's your software after all! :)
The box vs filled box i'm ok with it, but how about the "replica vs replica relocating blocks"? the colors are similar in the black background due to the small border and the dashes ... if the relocating blocks had a different color (gold, grey, dark-orange, even light-blue) it would help ... magenta and green are too similar due to the size. Notice that i have no problem with the live blocks vs live relocating blocks, only for the replicas that i have trouble identifying then.

Another workaround would be adding the "show only relocating shards" to the "show only unhealthy shards", that way it is easier to spot where are the shards relocating as the list is lot smaller
