### ISSUE TITLE
Make pid file optional and/or handle non-existing process better

### ISSUE THREAD

**Issue by walrusVision** [lmenezes/cerebro#14]
Can we make writing out the pid file optional? I am running it under supervisor which doesn't deal with external pid files.

Alternatively could cerebro check that the pid in the file is active and only error then. If the pid doesn't exist then it should rewrite the pid file with the new pid, otherwise error as before.

**Comment by lmenezes** [comment]
hey :)

under conf/application.conf, setting a property such as:
```
pidfile.path = "/dev/null"
```
should to the trick(of not writing a pid file).

**Comment by walrusVision** [comment]
That works perfectly! Thank you.
