### ISSUE TITLE
request: make application.conf auth directive ansible-friendly

### ISSUE THREAD

**Issue by nskalis** [lmenezes/cerebro#141]
Hi,

And thanks a lot for providing such a useful tool.

May I ask if it would be possible to provide the `application.conf`,
and more specifically, the `auth` directive either fully commented out or in a line ?
For example, like this:
```
#auth =
  # Example of LDAP authentication
  #type: ldap
    #settings: {
      #url = "ldap://host:port"
      #base-dn = "ou=active,ou=Employee"
      #method  = "simple"
      #user-domain = "domain.com"
    #}
  # Example of simple username/password authentication
  #type: basic
    #settings: {
      #username = "admin"
      #password = "1234"
    #}
#}
```
or 
make it an one-liner ?

The reason for asking this is because seems to be easy to implement, and most importantly,
we can adjust the configuration file using ansible in a reliable way (instead of commenting out a `}`).

PS. I am sorry if it sounds like a silly request

**Comment by dylanmei** [comment]
Ansible has sophisticated template system. You can use that rather than rely on the evolution of this file.

**Comment by nskalis** [comment]
Well, I would rather rely on the default conf file and modify its configuration directives rather than maintain my own conf file and keeping track if anything changed.

**Comment by moliware** [comment]
In the latest version it can be configured with environment variables; (see [here](https://github.com/lmenezes/cerebro#ldap-config)). So, I guess that makes it ansible friendly.

Feel free to reopen it if this is still an issue for you in the latest version.

Thank you!
