### ISSUE TITLE
Navigation: Logout doesn't use configured "basePath"

### ISSUE THREAD

**Issue by la3mmchen** [lmenezes/cerebro#142]
I'm using cerebro behind NGINX reverse proxy. 
Set: `basePath = "/cerebro/"` in application.conf.

Everything works except the Logout-Button that throws the user back to "/" and not "/cerebro/".

**Comment by lmenezes** [comment]
@la3mmchen which version are you using??

**Comment by la3mmchen** [comment]
@lmenezes i'm using v0.6.5.

**Comment by alexjfisher** [comment]
Same with v0.6.6.
logout button redirects me to /login instead of /basepath/login
I guess this is easy enough to fix?
https://github.com/lmenezes/cerebro/blob/fab0c1f52f40259f21e94063f157f9943f8b8617/app/controllers/AuthController.scala#L58
