### ISSUE TITLE
bin/cerebro or bin/cerebro.bat missing?

### ISSUE THREAD

**Issue by imran-uk** [lmenezes/cerebro#143]
I just downloaded the zip (cerebro-0.6.5.zip) and the README says to run cerebro I need:

`Run bin/cerebro(or bin/cerebro.bat if on Windows)`

Where can these be found? I think they are missing or the README is incorrect.

**Comment by Nefelim4ag** [comment]
@imran-uk, are you sure?
I downloaded:
https://github.com/lmenezes/cerebro/releases/download/v0.6.5/cerebro-0.6.5.zip
Unzip and see:
```
~ ls -l ~/Downloads/cerebro-0.6.5/bin/
total 16
-rw-r--r-- 1 nefelim4ag nefelim4ag 9206 May 10 17:07 cerebro
-rw-r--r-- 1 nefelim4ag nefelim4ag 4052 May 10 17:07 cerebro.bat
```

**Comment by ZengoWood** [comment]
Yeah - this threw me at first as well - I am guessing unlike kopf the source code needs to be compiled first, hence you either do that, or much more easily download from the releases page
