### ISSUE TITLE
Incorrect placement of JAVA_OPTS in Java command line

### ISSUE THREAD

**Issue by wolfgang-werner** [lmenezes/cerebro#144]
When an environment variable JAVA_OPTS exists, cerebro will not start because of the placement of the JAVA_OPTS expansion - this is interpreted as the Java main class to execute.

unset JAVA_OPTS and defining the Java options with the -J... Syntax works.

**Comment by moliware** [comment]
Hi,

I think this is not a problem any more. But feel free to reopen this issue if that is that is the case

Thanks!
