### ISSUE TITLE
How to turn on the debug for LDAP?

### ISSUE THREAD

**Issue by jockjiang** [lmenezes/cerebro#145]
the LDAP doesn't work for me, there is no error found in logs, I try turn on the debug for all in logback.xml, but I can not find LDAP related logs, how to turn on debug for LDAP feature?

**Comment by CraigFoote** [comment]
+1 Same here. Is there a guide anywhere as to what "method" etc. values should be?

**Comment by CraigFoote** [comment]
It seems I need a better example. I'm kinda new at LDAP settings but these don't match the properties we've set in elasticsearch.yml. I have access to an LDAP at ldap://myldap.com:389. I need to set a password to access it and would like a uid typed into the cerebro login form looked up from uid={uid},ou=people,ou=mycompany. What should my settings look like? Any help appreciated.

**Comment by jockjiang** [comment]
me, too.

**Comment by bhvr-fmarceau** [comment]
Indeed, some documentation would help to configure the AD conenction.

**Comment by CraigFoote** [comment]
Maybe I should be more specific. Can we get an update of  cerebro/conf/application.conf with complete representative key:values for the various authentication methods please? These should probably mirror elasticsearch.yml authentication properties if possible.

**Comment by jockjiang** [comment]
after I remove the basic auth type and keep just LDAP, and it will print out error message,  it failed on connecting to our AD server with SSL,
so I use the following to turn SSL debug, 
play.ws.ssl.debug = {
  ssl = true
  trustmanager = true
  keymanager = true
}
