### ISSUE TITLE
Can I setup basePath to other string than "/"?

### ISSUE THREAD

**Issue by jockjiang** [lmenezes/cerebro#146]
I try to setup proxy with Apache, I want to setup it the same as Kibana, but cerebro only support to set the basepath to "/", I have to use root Directory (/). can I use other Directory, such as /cerebro?

**Comment by mojira98** [comment]
Same problem here with v0.6.5
Even if i set 
```
# Application base path
basePath = "/cerebro"
```
There is a white page after login.

Thx

**Comment by fred-o** [comment]
Try setting a basePath with a trailing `/`

```
# Application base path
basePath = "/cerebro/"
```

**Comment by jockjiang** [comment]
basePath = "/cerebro/" still doesn't work for me.

**Comment by rahst12** [comment]
This bit me too... Having to do apache proxy rewrites for all the various endpoints

**Comment by lmenezes** [comment]
hey,

sorry for the long delay.

Can you tell me what your setup looks like exactly?

Running a standalone instance of cerebro, changing the basePath to **/cerebro/**, I can access it normally at **http://localhost:9000/cerebro/**.

**Comment by jockjiang** [comment]
Hi, 
I do the similar proxy as Kibana. I run Apache httpd on port 443, and configure the proxy as following
<Location "/cerebro">
    ProxyPass   http://127.0.0.1:9000
    ProxyPassReverse   http://127.0.0.1:9000
</Location>

the access url will be https://servername/cerebro/

I have to access https://servername/cerebro/login to the login page, once login, it will redirect me to https://servername/, then I need try https://servername/cerebro/ to reach the main page, click "Connect" to connect to elasticsearch.

before I login, when I access https://servername/cerebro/, it will redirect me to https://servername/login, since I don't set proxy for /login, I will get "Http/1.1 Service Unavailable"

**Comment by jockjiang** [comment]
this issue is fixed after change the settings in the proxy by adding /cerebro after 9000.
