### ISSUE TITLE
service not started after run from Dockerfile

### ISSUE THREAD

**Issue by kleuf** [lmenezes/cerebro#148]
hi, im building Cerebro for a Dockerfile.
After i created my image and did the run command, the service is not started, even though i end my Dockerfile with the following:
CMD [ "./usr/local/bin/cerebro "]
I have also tried the following:
CMD ["nohup ./usr/local/bin/cerebro &"]

im running on Linux version 4.8.0-51-generic

Any help will be appreciated.

**Comment by snuids** [comment]
You can do it like that :

FROM java:openjdk-8u72-jdk

COPY ./bin ./cerebro
WORKDIR ./cerebro/cerebro-0.6.3

ENTRYPOINT ./bin/cerebro

You must have a ./bin/cerebro-0.6.3 folder at the same level as the Dockerfile

**Comment by kleuf** [comment]
thank you @snuids
