### ISSUE TITLE
Add favicon with status color as in elasticsearch-kopf

### ISSUE THREAD

**Issue by xbgmsharp** [lmenezes/cerebro#15]
This was a nice to feature! would be nice to have it again.

**Comment by lmenezes** [comment]
@xbgmsharp this is actually already implemented. does it not work for you? which version are you using?

**Comment by xbgmsharp** [comment]
I am using FF and the latest dev verison including the Node and Indices page.

**Comment by Tonyko** [comment]
It's working for me (Chrome).

**Comment by Tonyko** [comment]
Check #26

**Comment by lmenezes** [comment]
fixed with https://github.com/lmenezes/cerebro/pull/26
