### ISSUE TITLE
Multiple aliases clutter

### ISSUE THREAD

**Issue by andrewkcarter** [lmenezes/cerebro#152]
We have 25+ aliases on some indexes with varying filters. In KOPF, it would show a couple on the overview page and then hide the remainder behind a +_N_. They could be seen via tooltip. In Cerebro they are all visible, and it was much nicer to have the KOPF display implementation.

**Comment by johnnelus** [comment]
I would like a solution for this as well. I have multiples indices with thousands of aliases (alias per customer with routing and filtering) and Cerebro is getting slow because it shows all of them
