### ISSUE TITLE
Inconsistent startup behavior on AWS across regions

### ISSUE THREAD

**Issue by Jaff** [lmenezes/cerebro#155]
Hi,

Setting up an elasticsearch cluster (3 nodes) with ES-5.4.0 and cerebro-0.6.5, I have a daemon launch configured identically on all three nodes. OS is Ubuntu 14.04.4. In two cases, the application starts and connects, but on the first node, I see a connect failure, then the launch script retries and fails due to persistent RUNNING_PID file. Error displayed is:
[error] p.c.s.NettyServer - Failed to listen for HTTP on /0.0.0.0:9300!

Where the application succeeds, I see this:
[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9300

I am perplexed as to why it listens on ipv6 on two nodes, but ipv4 on the one. I even added -Djava.net.preferIPv6Addresses=true to the launch script with no success.

**Comment by arohter** [comment]
You cannot use port 9300 for cerebro, as ES uses this for tcp transport.

**Comment by Jaff** [comment]
Closing, 'pilot error'
