### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by seanziee** [lmenezes/cerebro#158]
Sorry for the noob question, but I can't seem to figure out what cerebro version goes with what ES version. Is there a key somewhere?

**Comment by bhvr-fmarceau** [comment]
Cerebro = ES 5.X
KOPF = ES 1.X & ES 2.X

**Comment by seanziee** [comment]
So if I have ES 5.3.2, which cerebro would I download? Or the most recent version works for all 5.X?

**Comment by lmenezes** [comment]
@seanziee most recent version should work for all, also for 2.X.
