### ISSUE TITLE
Ask credentials with registered hosts

### ISSUE THREAD

**Issue by yoann-bellet** [lmenezes/cerebro#169]
Hello,

I wonder if it's possible on configuration to register an host, but ask user to authenticate ?

for instance  : 
![hosts](https://user-images.githubusercontent.com/7566581/27595796-f3521cc4-5b5d-11e7-8665-ff8a77a35f7a.PNG)

When I click on cluster I can't see any information because i'm not authenticated with our authentication Backend solution : 

![auth_impossible](https://user-images.githubusercontent.com/7566581/27595890-3af1ce62-5b5e-11e7-859a-f06fb1b2dc6c.PNG)

It works if i use input but I have to enter host (here https://localhost:9200 i use an nginx reverse proxy, and after credentials, but admin users don't want to type hostname every time we use cerebro supervision)

Best regards.

**Comment by lmenezes** [comment]
this should now prompt for username/password if cluster requires authentication, but none is provided on the config file :)
