### ISSUE TITLE
Error while loading data - No handler found for uri

### ISSUE THREAD

**Issue by MonaiThang** [lmenezes/cerebro#170]
I followed the installation steps in readme but got error when connecting my local Elasticsearch as below:
{
  "error": "No handler found for uri [//_cluster/state/master_node,routing_table,routing_nodes,blocks] and method [GET]"
}

Both cerebro and Elasticsearch are running on Windows 10.

**Comment by lmenezes** [comment]
you just need to remove the trailing / from your host. I will anyway add a fix to automatically remove these trailing /.
