### ISSUE TITLE
self signed certificates 

### ISSUE THREAD

**Issue by screwyy** [lmenezes/cerebro#175]
Hi, is there an option for host auth to add certificates (root ca, ca, key ) and the possibility to add something like "validate_certs: false" ?

**Comment by webeks** [comment]
search across all issues got me this https://github.com/lmenezes/cerebro/issues/127

`play.ws.ssl.loose.acceptAnyCertificate = true`


Havent found a way to import my own CA yet.

**Comment by johnseekins** [comment]
https://github.com/lmenezes/cerebro/issues/6 describes how to add a self-signed CA.

Basically:
```
play.ws.ssl {
  trustManager = {
    stores = [
      { type = "PEM", path = "<cert>" }
    ]
  }
}

**Comment by lmenezes** [comment]
@screwyy did you try what @johnseekins suggests on #6?
