### ISSUE TITLE
Core Dump

### ISSUE THREAD

**Issue by cdenneen** [lmenezes/cerebro#185]
```
[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[CodeBlob (0x000000010b1bae10)]
Framesize: 0
BufferBlob (0x000000010b1bae10) used for StubRoutines (2)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:834), pid=17498, tid=33539
#  fatal error: exception happened outside interpreter, nmethods and vtable stubs at pc 0x000000010b1bd36f
#
# JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode bsd-amd64 compressed oops)
# Core dump written. Default location: /cores/core or core.17498
#
# An error report file with more information is saved as:
# /Users/cdenneen/temp/cerebro-0.6.5/hs_err_pid17498.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[1]    17498 abort (core dumped)  ./bin/cerebro
```

**Comment by lmenezes** [comment]
@cdenneen I really can't do anything with this info, sorry. Is this a recurring issue, or did it happen a single time? Also, which os are you using?

**Comment by cdenneen** [comment]
Release worked fine until my cluster was loaded with a ton of data. Now
with this much data it crashes. So maybe there is some limit as to the # of
indices or shards before it dumps?

**Comment by lmenezes** [comment]
@cdenneen would it be possible to tell me how many indices/shards/aliases and etc your cluster has? and also, how big are the mappings and so on?
Ideally, if you could give me a script that recreates your indices with the actual config and so on(but not the data itself), that would be great(although I imagine you might have sensitive info there).

**Comment by lmenezes** [comment]
ok, I take this as the issue not being relevant anymore.
