### ISSUE TITLE
cerebro running in Docker container does not pass signals

### ISSUE THREAD

**Issue by jcassee** [lmenezes/cerebro#191]
When I run cerebro in a Docker container, the `docker stop` command needs to kill the container. I think this is because the `bin/cerebro` script does not pass signals to the JVM.

To reproduce:

```
docker run -d --rm --name=cerebro goabout/cerebro
docker stop cerebro
```

**Comment by dylanmei** [comment]
You should open an issue with the folks who created this image: https://github.com/goabout/docker-cerebro

Alternatively, you could use another image -- I can vouch for this one: https://hub.docker.com/r/dylanmei/cerebro/

**Comment by jcassee** [comment]
Indeed, sorry!
