### ISSUE TITLE
Set log path via config file

### ISSUE THREAD

**Issue by iyuvalk** [lmenezes/cerebro#195]
Hi,

Is it possible to set the logging path for Cerebro via the config file to something other than the default logs/application.log?

**Comment by tlied2** [comment]
@iyuvalk The logger is configurable by editing conf/logback.xml. Hopefully that is what you are looking for, it is very flexible, and changing the path should be as simple as replacing logs/application.log as necessary.

**Comment by moliware** [comment]
@tlied2 is right. This is the best solution (at least for now) .

Thanks!
