### ISSUE TITLE
[Feature Request] Prompt for credentials when elasticsearch requires authentication

### ISSUE THREAD

**Issue by jfwm2** [lmenezes/cerebro#199]
Hello

It is currently possible to configure a list of known hosts in the configuration file. When a host requires authentication, the connection fails if the corresponding 'auth' section does not exist.
Would it be possible that cerebro prompt for a login/password in such a situation?
This would allow us not to configure single static credentials for each host, but instead each user would be required to put her/his own credentials, making easier to track access on the elasticsearch authentication backend.

Thanks for your understanding
Jean-Francois Weber-Marx
jf.webermarx@criteo.com

**Comment by ceeeekay** [comment]
0.7.2 works great. Thanks!
