### ISSUE TITLE
Interface: Sort host doesn't change host column order

### ISSUE THREAD

**Issue by ceeeekay** [lmenezes/cerebro#2]
Clicking on sort host [a-z] changes the index columns, but not the host column. Host are always listed in descending order.

Nice work so far though :smiley_cat: 

Firefox 47.0
Chrome 51.0.2704.106
Ubuntu 14.04

**Comment by adamlepkowski** [comment]
I wanted to fix it but I think it's not a bug it's a feature  :) 

This [a-z] is available in host column but yes it sorts index names not a host names I think author did it on purpose. As you can notice indexes names are presented in columns and their amount depends on node configuration so where we should put sorting icon for indexes looking from UI perspective? In my opinion we should have two icons in the host column but maybe author should share his opinion and after that I can implement it ;)

**Comment by ceeeekay** [comment]
Hm, true. However there are a couple of confusing things here:

* The host order is inverted. Mine are listed in descending order, with no way I can see to change that.
* The arrow on the A-Z selector is vertical, implying it's going to sort things appearing in the direction (e.g., the hosts)

I've just checked Kopf and it does indeed sort the index names, so the behaviour is the same. I guess I've never used it before, and only noticed this because I was trying to fix the hosts being in the wrong order.

**Comment by lmenezes** [comment]
hey there,
actually @adamlepkowski is right, and it was never really intended to sort the hosts. mostly, because most people won't have that many hosts. indices on the contrary, someone using kibana/logstash for example might have hundreds, and then sorting here really helps. but I do agree the icon and perhaps its position can be highly misleading... 

at the moment I'm just trying to make cerebro more or less feature equivalent with kopf, but later on i will tackle this smaller issues. 

thanks for the feedback :)

**Comment by adamlepkowski** [comment]
@lmenezes do you need any help with development?

**Comment by lmenezes** [comment]
sure, that would be great :)
At the moment I'm finishing developing the "analysis" section, similar to the one in kopf. 
I'm also at this point starting to organise the code a bit. So, just let me know which section(from the ones currently on kopf) you would like to develop, and we can talk about it.
I will also soon perhaps create issues for all the missing features, and also for features that would be nice to have.

**Comment by adamlepkowski** [comment]
Great:) I will help with pleasure. Can you follow me on twitter becuase then I can send you a private message ;)

**Comment by adamlepkowski** [comment]
btw. @lmenezes i'm working on nodes page
