### ISSUE TITLE
Java Heap Space

### ISSUE THREAD

**Issue by orinciog** [lmenezes/cerebro#200]
Hello!

I'm having a cluster of  23 nodes, 1,365 indices, 13,511 shards and I'm trying to use Cerebro for this cluster, but each time when I navigate to nodes tab, cerebro throws "java.lang.OutOfMemoryError: Java heap space" and is giving 500 Internal server error.

Kopf is working fine with this cluster.

Thank you.

**Comment by lmenezes** [comment]
is the overview page working?

**Comment by orinciog** [comment]
Yes, it is working.

**Comment by lmenezes** [comment]
Could you also tell me which OS you are using and how much heap space you are giving to cerebro?

**Comment by lmenezes** [comment]
is this still an issue?

**Comment by orinciog** [comment]
Sorry, but I switched back to kopf, due to heavy load caused by cerebro on our cluster, and I can't test it right now. 

But to answer to our old question, I was using Ubuntu 16.04 with default configurations for cerebro.
