### ISSUE TITLE
Overview mouse over tooltip on node stats doesn't appear

### ISSUE THREAD

**Issue by megakid** [lmenezes/cerebro#21]
In Kopf when hovering over the stats for each node (such as the `disk`, `cpu`, `load` etc), a tool tip appears with the raw readings.  Cerebro doesn't seem to do this - those stats are quite useful to give some drill down if you spot the horizontal bars growing etc.

**Comment by ayoldi-bshg** [comment]
+1 to that. It was a great feature. Thanks anyway for such a useful tool ;)
