### ISSUE TITLE
autocomplete offset on linux

### ISSUE THREAD

**Issue by redxtech** [lmenezes/cerebro#210]
When I use cerebro on arch linux, it puts the autocomplete text on an offset, so that it looks pretty weird.

[Here's](https://i.imgur.com/kJ3NHN7.png) an image.

I'm willing to do the fix for this, as I am interested in contributing, however as I am unfamiliar with the codebase you will have to explain to me where the code that causes this is.

Thanks :)

**Comment by lmenezes** [comment]
@redxtech great :) 
I can point out to where the problem is, but I think the img you uploaded is not the one you actually meant ;)

**Comment by redxtech** [comment]
Yeah that's the one I meant, but I guess it wsan't cropped properly. [Here's](https://i.imgur.com/kJ3NHN7.png) a properly cropped version.
And that would be great, would you point it out?

**Comment by lmenezes** [comment]
@redxtech sorry again, but I honestly don't understand the image :(
Is this really the right picture?

![](https://i.imgur.com/kJ3NHN7.png)

**Comment by lmenezes** [comment]
@redxtech oh my god, I just realised something: there is another project called cerebro, and I guess that's the one you meant: https://github.com/KELiON/cerebro

**Comment by redxtech** [comment]
oh shoot, that's hilarious. i better go and move this issue to that project. 
thanks :)
