### ISSUE TITLE
Cerebro and S3 snapshots

### ISSUE THREAD

**Issue by AGirin** [lmenezes/cerebro#212]
Does cerbro working with snapshot stored on AWS S3? We are using kopf plugin and we can browse and restore all snapshots. With cerebro it is not working. We can see all our snapshots but when we click on restore - nothing happens (same snapshots work just fine with kopf). We found one snapshot that is actually opening additional properties like rename pattern etc. But other snapshots do not do anything. This is true for all three cluster that we run.

We are using 0.6.8.

Thanks!

**Comment by dchauviere** [comment]
Same problem with 0.7.2 !
This happens when snapshot's name contains dots !

**Comment by WorLord** [comment]
Same problem here, would love to see this working again.

**Comment by moliware** [comment]
Fixed in https://github.com/lmenezes/cerebro/pull/351

Thank you for reporting. In the next release it will be available
