### ISSUE TITLE
[bug] If "show only affected indices" is selected while cluster state changes to green, no indices are shown

### ISSUE THREAD

**Issue by RogierSchuring** [lmenezes/cerebro#217]
Found a minor bug that is present since at least 0.6.5:
If you select "show only affected indices" when shards are relocating or initializing, you don't see any indices when cluster state changes to green (all are hidden, because none are affected).
There is no possibility to see all indices again except changing view (go to "nodes" view and back).
It would be nice (and I think this was the case with Kopf) if it returns to the show all indices view.
P.s., thanks for this tool, it's really great!

**Comment by lmenezes** [comment]
@RogierSchuring yep, you are right. I will fix this asap and include in the next release.
