### ISSUE TITLE
Question: Disk color threshold in the overview

### ISSUE THREAD

**Issue by 123dev** [lmenezes/cerebro#220]
Hi,

We'd like to understand how the Disk color is determined?
The different colors and their thresholds
Is it possible to configure these?
For example we'd like to display yellow when the disk usage is at or more than of **cluster.routing.allocation.disk.watermark.low**
and red at or more than of
**cluster.routing.allocation.disk.watermark.high**

It would also be nice if the hovering on disk displayed in percentage usage rather than bytes, specially if 
cluster.routing.allocation.disk.watermark is set to a percentage rather than bytes.

Thanks

**Comment by lmenezes** [comment]
@123dev hey there. At the moment this is a static value of 75%. 

What you ask is doable and I plan on doing it(someone asked about it before): https://github.com/lmenezes/cerebro/issues/1

I'm hoping to have sometime during this next week to close a few issues and create a new release. 

If this is ok for you, I will just close this issue and reference it from the other one.

**Comment by 123dev** [comment]
Absolutely.
Thanks for working on it.
