### ISSUE TITLE
the cerbro when manager indices about the indices settings not output the all settings

### ISSUE THREAD

**Issue by zqc0512** [lmenezes/cerebro#221]
@lmenezes 
the cerebro when manager indices about the indices settings not output the all settings about use curl XGET or rest in cerebro 
as

the indices settings  not  full about it , i wan't to change  as max_thread_count ...

**Comment by lmenezes** [comment]
@zqc0512 which setting do you mean exactly? merge.scheduler.max_thread_count? If so, this is now(since v0.8.0) available.
