### ISSUE TITLE
building the project

### ISSUE THREAD

**Issue by jmwilkinson** [lmenezes/cerebro#224]
I am struggling with building cerebro from source. 

I figured it may be something like `sbt clean compile package`, but that just seems to make a .jar. My preference is to actually make the equivalent of the releasable tar.gz with the bin directory and executable.

What steps are involved in doing this?

**Comment by lmenezes** [comment]
@jmwilkinson what do you want to do exactly?

**sbt compile** will build it from source, and you can run it locally with **sbt run**

If what you want is to create the distribution file, you need to run:
**sbt universal:packageBin** - creates a zip file
**universal:packageZipTarball** - creates a tgz file

Hope this helps :)

**Comment by jmwilkinson** [comment]
The second one, thanks so much.
