### ISSUE TITLE
when use 0.7.1 can't show the affected inidces.

### ISSUE THREAD

**Issue by zqc0512** [lmenezes/cerebro#225]
use show only affected indices can't show the affected inidces.
![image](https://user-images.githubusercontent.com/25192261/32152168-5d6191d8-bd5d-11e7-854d-6c43c8a0da77.png)

**Comment by lmenezes** [comment]
@zqc0512 could it be that the "affected" indices are special indices, and hidden because of the unchecked **.special** checkbox?

**Comment by zqc0512** [comment]
this is not closed and .special indices .
you can test it. when cluster rebanlance or start.
@lmenezes

**Comment by weirdnose** [comment]
Can confirm. The violet shard information is missing as well. The shards read from are no longer indicated if I am not mistaken.

**Comment by zaakiy** [comment]
@lmenezes "affected" indices are indices which are currently in a transition state, i.e., either the primary or replica is not allocated or is being moved

**Comment by rhaig** [comment]
noticed this when adding replicas.

**Comment by lmenezes** [comment]
sorry about that, will try to prepare a fix asap.
