### ISSUE TITLE
unable to run cerebro-0.7.1 with error message "Unable to access jarfile "

### ISSUE THREAD

**Issue by ravipalaparthi** [lmenezes/cerebro#226]
Hi,

1. Downloaded latest zip (version: cerebro-0.7.1) from the GitHub.
2. extracted and tried to start the service.
C:\user1\cerebro-0.7.1\bin>cerebro
Error: Unable to access jarfile C:\user1\

Am I missing anything?
Please help me in resolving this issue.

**Comment by tonykoval** [comment]
Did you download [link](https://github.com/lmenezes/cerebro/releases/download/v0.7.1/cerebro-0.7.1.zip)? Unpack and try run `bin/cerebro.bat` (windows)

**Comment by ravipalaparthi** [comment]
Yes but somehow it got corrupted.

I downloaded from the provided link and its working. Thanks for the quick response.
