### ISSUE TITLE
builds failing on dockerhub

### ISSUE THREAD

**Issue by andrewmcgilvray** [lmenezes/cerebro#227]
https://hub.docker.com/r/yannart/cerebro/builds/

**Comment by qoomon** [comment]
this one works and has the current version 0.7.1
https://hub.docker.com/r/qoomon/docker-cerebro/

**Comment by moliware** [comment]
Cerebro has now its own repository in docker-hub:
https://hub.docker.com/r/lmenezes/cerebro/builds/

Thank you for looking for alternatives in the mean time :)
