### ISSUE TITLE
Support for Elastic 6.x

### ISSUE THREAD

**Issue by Lunatictwo** [lmenezes/cerebro#229]
Many new features in 6.x ,what's the plan to support it?

**Comment by leschNUX** [comment]
one of it is the new param:
cluster.routing.allocation.disk.watermark.flood_stage

**Comment by lmenezes** [comment]
@Lunatictwo I have no plans at the moment to add new features, although you are more than welcome to create feature requests. Not sure when I would have time to work on them tough.
