### ISSUE TITLE
Elasticsearch 6.0 compatibility

### ISSUE THREAD

**Issue by piotrkochan** [lmenezes/cerebro#232]
Cerebro is not compatible with Elasticsearch 6.0 - for example when I try to create new repository ES returns error:

`{"status":500,"body":{"error":{"root_cause":[{"type":"repository_exception","reason":"[backup_1] location [/var/test] doesn't match any of the locations specified by path.repo because this setting is empty"}],"type":"repository_exception","reason":"[backup_1] failed to create repository","caused_by":{"type":"repository_exception","reason":"[backup_1] location [/var/test] doesn't match any of the locations specified by path.repo because this setting is empty"}},"status":500}}`

Checked at v0.7.1

**Comment by lmenezes** [comment]
@piotrkochan this just means you are missing the path.repo property on your config file. This error would be the same for 5.X if such property is not set.

**Comment by piotrkochan** [comment]
But there is more. Like "analyze by field type" returns:

`{"status":406,"body":{"error":"Content-Type header [text/plain; charset=utf-8] is not supported","status":406}}`

This is related to 6.0 REST API changes: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/breaking_60_rest_changes.html#_content_type_auto_detection

**Comment by lmenezes** [comment]
@piotrkochan I did a quick check, and it seems the analyse module was the only thing broken with ES 6.0, but please let me know if you find anything else.

**Comment by Stas-PerimeterX** [comment]
curl -XPOST 'http://10.10.0.10:9200/syslogs/settings' -d '{
 "index": {
  "number_of_replicas": 2
 }
}'
Sending this one is also causing:
{
  "error": "Content-Type header [text/plain; charset=utf-8] is not supported",
  "status": 406
}

When trying to change the replicas count through UI, it alerts "Error while saving settings"

**Comment by raulk89** [comment]
Hi

Shouldn’t you be using -XPUT instead..?

Regards
Raul

**Comment by Stas-PerimeterX** [comment]
@raulk89, same effect

**Comment by vchan2002** [comment]
The issue is that it appears that elasticsearch is more aware of the header that you're sending, and outright rejects plain headers.. it needs to have a json header....

https://github.com/elastic/kibana/issues/10504

**Comment by lmenezes** [comment]
@Stas-PerimeterX through the UI where? Using the index settings section, this is working fine.

**Comment by Stas-PerimeterX** [comment]
@lmenezes , from cluster settings.

**Comment by Stas-PerimeterX** [comment]
@lmenezes , sorry probably version problem, the docker I have been using is 0.6.4

**Comment by lmenezes** [comment]
@ebdavison which version are you using? this issue has been fixed, or maybe this is something I overlooked?
