### ISSUE TITLE
When clicking nodes section at top get error message

### ISSUE THREAD

**Issue by ed0724** [lmenezes/cerebro#234]
Clicking the nodes stat button just gives error message:

  Error while loading nodes data

**Comment by ed0724** [comment]
[error] application - Error processing request [path: /nodes, body: {"host":"tyadr_logging"}]

**Comment by lmenezes** [comment]
@ed0724 what version of ES, cerebro and OS are you using? And which nodes stat button is this?

**Comment by ed0724** [comment]
ES - 5.5.0-1
Cerebro - 0.7.1
OS - Centos7 3.10.0-514.6.1.el7.x86_64

On the web page in the top bar to the right of the cerebro icon.  There a tiny stack icon with the word "nodes" next to it.  The page shows the node stats.

**Comment by ed0724** [comment]
Should this be populated with all the ES nodes in the stack ?
# A list of known hosts
hosts = [
  #{
  #  host = "http://localhost:9200"
  #  name = "Some Cluster"
#},

**Comment by ed0724** [comment]
Error while loading nodes data
{
  "error": "JsResultException(errors:List((,List(ValidationError(List('sqHQU1W-RlS3WTTG0D_7Gg' is undefined on object: {\"jeW2LpoTQJuwMWg6hnuAWQ\":>....................

**Comment by lmenezes** [comment]
Could you get the output of:
```
/_nodes/_all/jvm,os?human=true
/_nodes/stats/jvm,os,fs,process?human=true
/_cat/master?format=json
```
I believe the list of nodes returned by these calls is not consistent.

**Comment by ed0724** [comment]
here are the outputs

[REST cmd outputs.txt](https://github.com/lmenezes/cerebro/files/1518756/REST.cmd.outputs.txt)

**Comment by ed0724** [comment]
Why am I seeing this:

Nov 30 13:07:22 es01 systemd[1]: Started Cerebro.
Nov 30 13:07:22 es01 systemd[1]: Starting Cerebro...
Nov 30 13:07:24 es01 cerebro[2706]: WARNING: An illegal reflective access operation has occurred
Nov 30 13:07:24 es01 cerebro[2706]: WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/opt/cerebro-0.7.1/lib/com.goog...ctionDomain)
Nov 30 13:07:24 es01 cerebro[2706]: WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
Nov 30 13:07:24 es01 cerebro[2706]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Nov 30 13:07:24 es01 cerebro[2706]: WARNING: All illegal access operations will be denied in a future release

**Comment by ed0724** [comment]
I have the "nodes" page issue fixed, working now.   However when shards are reinitializing and I select "show only affected indices" it does not show any indices.

**Comment by lmenezes** [comment]
@ed0724 upgrade to 0.7.2, this last issue has been fixed already.
