### ISSUE TITLE
the count data is not same with es commd line count  why?

### ISSUE THREAD

**Issue by zqc0512** [lmenezes/cerebro#248]
is es 5.6.5
 curl -XGET 'http://XXX.XXX.XXX.XXX:9200/xxx/_count?pretty'
{
  "count" : **654763337**,
  "_shards" : {
    "total" : 36,
    "successful" : 36,
    "skipped" : 0,
    "failed" : 0
  }
}

but in Cerebro 
    "primaries": {
      "docs": {
        "count": **1576307121**,
        "deleted": 0
      },
@lmenezes 
thanks.

**Comment by lmenezes** [comment]
I cannot reproduce this at all, but it seems you are hitting different APIs. 

What path do you use in cerebro?

**Comment by lmenezes** [comment]
ok, I'm assuming this is no longer an issue.
