### ISSUE TITLE
LDAP authentication: only if user is member of certain AD group

### ISSUE THREAD

**Issue by raulk89** [lmenezes/cerebro#259]
Hi

This post is probably in the wrong place, but I did not find a "community" to ask these questions.

I was wondering, is it possible to modify **application.conf** so that only ldap users, who belong to a certain AD group, can successfully authenticate themselves..?
And if user is present in AD, but not member of certain group, then it can not authenticate themselves.

Regards
Raul

**Comment by moliware** [comment]
Hi!

This is now supported in 0.8.2 see: https://github.com/lmenezes/cerebro#ldap-config

Thanks!
