### ISSUE TITLE
Can not restore snaphots with dot in name

### ISSUE THREAD

**Issue by qoomon** [lmenezes/cerebro#261]
It is not possible to open snapshot restore dialogue if snapshot name contains dots.
No console error occur.

I refer to click on following gui element at `.../#/snapshot`

```xml
<i class="fa fa-download normal-action pull-right" data-toggle="collapse" href="#log-2018.01.17_details" aria-expanded="true">
</i>
```

**Comment by hollowimage** [comment]
+1

**Comment by KundK** [comment]
same here :(
