### ISSUE TITLE
Not an issue: Admin page

### ISSUE THREAD

**Issue by BentCoder** [lmenezes/cerebro#267]
Hi,

Is there any plan to implement login page to secure the site?

Thanks

**Comment by defect** [comment]
If you enable one of the authentication features (see https://github.com/lmenezes/cerebro/blob/master/conf/application.conf#L25) you'll get a login page. Or is that not what you're looking for?

**Comment by BentCoder** [comment]
That's exactly what I wanted. Thank you.
