### ISSUE TITLE
feature request: action settings (auto_create_index, destructive_requires_name)

### ISSUE THREAD

**Issue by okke-formsma** [lmenezes/cerebro#277]
Hi,

first of all, thanks for the amazing piece of software that is cerebro.

Could you have a look at the following. I'd love to have an easy way in the GUI to edit the 'action' settings: auto_create_index and destructive_requires_name.

```
{
  "transient": {
    "action": {
      "auto_create_index": "*",
      "destructive_requires_name": "true"
    }
 }
}
```

**Comment by lmenezes** [comment]
@okke-formsma I will be soon working on supporting all settings that are returned through 
```
/_cluster/settings?flat_settings=true&include_defaults=true
```
and as both these settings are returned through this API, they will then be supported.

I'm hoping to have sometime in the next few days, but don't take my word for it :)
