### ISSUE TITLE
incompatible with ubuntu `openjdk-9-jre-headless`

### ISSUE THREAD

**Issue by shadiakiki1986** [lmenezes/cerebro#278]
Steps to reproduce on ubuntu 16.05

- `sudo apt-get install openjdk-9-jre-headless`
- downloaded cerebro release 0.7.2
-  extract and run `./bin/cerebro` 

Expected to work, but actual output is

> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:31)
> 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:22)
> 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:16)
> 	at slick.jdbc.JdbcDataSource$.forConfig(JdbcDataSource.scala:41)
> 	at slick.jdbc.JdbcBackend$DatabaseFactoryDef$class.forConfig(JdbcBackend.scala:268)
> 	at slick.jdbc.JdbcBackend$$anon$3.forConfig(JdbcBackend.scala:33)
> 	at slick.jdbc.JdbcBackend$class.createDatabase(JdbcBackend.scala:36)
> 	at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:498)
> 	at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:498)
> 	at slick.backend.DatabaseConfig$$anon$1.db$lzycompute(DatabaseConfig.scala:73)
> 	at slick.backend.DatabaseConfig$$anon$1.db(DatabaseConfig.scala:72)
> 	at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:57)
> 	at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:60)
> 	at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:124)
> 	at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:102)
> 	at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:117)
> 	at play.api.db.evolutions.DefaultEvolutionsApi.scripts(EvolutionsApi.scala:82)
> 	at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:53)
> 	at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:99)
> 	at play.api.db.evolutions.ApplicationEvolutions.play$api$db$evolutions$ApplicationEvolutions$$runEvolutions(ApplicationEvolutions.scala:49)
> 	at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
> 	at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
> 	at scala.collection.immutable.Stream.foreach(Stream.scala:594)
> 	at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:42)
> 	at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:150)
> 	at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:53)
> 	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:53)
> 	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:44)
> 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
> 	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
> 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
> 	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
> 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
> 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
> 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
> 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
> 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
> 	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
> 	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
> 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
> 	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
> 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
> 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
> 	at com.google.inject.Guice.createInjector(Guice.java:96)
> 	at com.google.inject.Guice.createInjector(Guice.java:84)
> 	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
> 	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
> 	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
> 	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:47)
> 	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
> 	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
> Caused by: java.lang.RuntimeException: Fatal exception during proxy generation
> 	at com.zaxxer.hikari.proxy.JavassistProxyFactory.<clinit>(JavassistProxyFactory.java:61)
> 	... 51 more
> Caused by: javassist.NotFoundException: java.sql.Wrapper
> 	at javassist.ClassPool.get(ClassPool.java:452)
> 	at javassist.ClassPool.getCtClass(ClassPool.java:517)
> 	at com.zaxxer.hikari.proxy.JavassistProxyFactory.generateProxyClass(JavassistProxyFactory.java:143)
> 	at com.zaxxer.hikari.proxy.JavassistProxyFactory.<init>(JavassistProxyFactory.java:84)
> 	at com.zaxxer.hikari.proxy.JavassistProxyFactory.<clinit>(JavassistProxyFactory.java:57)
> 	... 51 more

**Comment by tlied2** [comment]
Expecting Java 9 to work at this stage seems a bit of a stretch, as the Play Framework is still working on support as is Scala itself (though some pieces have been implemented). That said, I figured I'd do some simple testing (yay docker) and the results were interesting, perhaps even surprising (I expected some dependency updates and at least a rebuild would be needed).

Ubuntu 16.04 - does not work, as you describe (just use Java 8, it is still supported until next year)

All the following print some reflection warnings at startup, but do indeed start, and appear to work:
Fedora 27
Ubuntu 17.10
Ubuntu 18.04 (next LTS, due for release this month it appears) - also works with the packages they have labeled as openjdk-11 (which isn't due for release for several months, so seemed odd it would be in the list), which displays a Java 10 version in java -version (which makes more sense as Java 10 has been released)

Hope that helps.

**Comment by lmenezes** [comment]
@shadiakiki1986 hey there. as @tlied2 said, support for java 9 from both play/scala is still not 100%, and there is not much I can do about this.

I will upgrade dependencies as soon as they are available, and hopefully soon this will run fine on java 9.
