### ISSUE TITLE
Issue with Cerebro 0.7.3

### ISSUE THREAD

**Issue by odsca** [lmenezes/cerebro#285]
Hey Guys,

Im a noob at this and have a few issues/questions.

1. After downloading Cerebro, where do I extract the contents of the zip file (I currently have it extracted on my desktop)?

2. When i run the .bat file, the following messages return - is this normal?
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/xxxxxxx/Desktop/cerebro-0.7.3/lib/com.google.inject.guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.St
ring,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] play.api.Play - Application started (Prod)
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

3. It's asking for username and password, what do i use?
![image](https://user-images.githubusercontent.com/38543908/39022629-4b7235b2-43eb-11e8-8584-afef08258062.png)

I'm running Elastic 6.2.2 w/ x-pack installed.

Thanks in advance!

**Comment by pascalgrimaud** [comment]
I think it's not related to this project.
Have a look at the security part: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docker.html

**Comment by moliware** [comment]
Yep, I think it's what @pascalgrimaud suggested. I close the issue for now.
