### ISSUE TITLE
Authentication option missing in 0.7.3

### ISSUE THREAD

**Issue by sdba2** [lmenezes/cerebro#289]
hi,
in version 0.6.5 there was an "Authentication" option to add user & password to authenticate to elastic (we are using the readonlyrest plugin) but the new version (0.7.3) is missing this option.
how can i authenticate using user & pw ?

**Comment by trondhindenes** [comment]
So much this. 0.7.3 supports a config file, which is a pain when using Docker.

**Comment by lmenezes** [comment]
@sdba2 You should still be able to try and connect to the host, except that the credentials check would happen after this first connection attempt, displaying then the user/password.
