### ISSUE TITLE
Doesn't start on Ubuntu 18.04, likely because of java version parsing

### ISSUE THREAD

**Issue by trondhindenes** [lmenezes/cerebro#290]
```
cerebro-0.7.3/bin/cerebro

The java installation you have is not up to date
requires at least version 1.6+, you have
version 10.0.1

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .
```

**Comment by logotype** [comment]
yes that appears to be the case. as a temporary workaround i just deleted the function java_version_check in the `bin/cerebro` bash script, and it starts fine.

**Comment by toadjaune** [comment]
Just had the same issue, with cerebro `0.8.1`.
I worked around it by uninstalling `default-jdk`, and installing `openjdk-8-jdk`

**Comment by omega** [comment]
you can also run it with `./bin/cerebro -no-version-check` to skip the version checking

**Comment by moliware** [comment]
Thanks for reporting! Unfortunately this is a play problem so, @omega's workaround is the only way to go.

Fortunately we have just done #352 and this  should not be a problem in future releases
