### ISSUE TITLE
ERROR SQLTransientConnectionException: db - Connection is not available

### ISSUE THREAD

**Issue by sonfrau** [lmenezes/cerebro#292]
I've installed the lastest version 0.7.3 but when I try to start this service I've got this error:

```
Oops, cannot start the server.
May 09 10:53:28 cerebropci cerebro[36727]: java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 1025ms.
```

Please, any clue will be wellcoming.

Thanks and kind regards

**Comment by jaredstehler** [comment]
I seemed to resolve this by granting my container more cpu units. It was failing with `256`, but succeeds with `1024`.

**Comment by sonfrau** [comment]
I haven't been using a dockerized cerebro and the problem was there so I can't modify the available cpu units.

**Comment by sonfrau** [comment]
I must rectify. We was using a small Azure VM. We have scaled it to a bigger size and the process has started working.

So, there is a direct relation between machine resources and this problem.

Thanks for your clue and kind regards

**Comment by jazoom** [comment]
@jaredstehler I don't know how you worked out it needed more CPU based on that error message, but that worked for me too. Thanks.
