### ISSUE TITLE
ES replica of Index shown miss??

### ISSUE THREAD

**Issue by lynchlee** [lmenezes/cerebro#296]
My index setting is 
{
  "test_idx1": {
    "settings": {
      "index": {
        "creation_date": "1527422039755",
        "number_of_shards": "5",
        "number_of_replicas": "2",
        "uuid": "WYm0BXXERiCsslc-As0j2w",
        "version": {
          "created": "5060999"
        },
        "provided_name": "test_idx1"
      }
    }
  }
}

But, I got shown index number of UI cerebro is 
`test_idx1`
`shards: 5 * 3 | docs: 0 | size: 810.00b`

Cloud someone can explain for me , what the "shards: 5 * 3" means ?

ES version: 5.6.9
cerebro: 0.7.3

many thanks

**Comment by pc-jedi** [comment]
`number_of_replicas` means additional shards besides the primary. See [Shards and Replicas](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/_basic_concepts.html#getting-started-shards-and-replicas).
Therefor you have 2 replicas and 1 primary for of each of your 5 shards.

**Comment by lmenezes** [comment]
exactly what @pc-jedi said (thanks 👍 )
