### ISSUE TITLE
Explain benefits of cerebro over kopf in README

### ISSUE THREAD

**Issue by xrl** [lmenezes/cerebro#3]
Hi, we're avid fans of Kopf on my project and we saw an off-hand mention of cerebro in the elasticsearch blog ( https://www.elastic.co/blog/running-site-plugins-with-elasticsearch-5-0 ). Can you put a few words in the README about the benefits of cerebro? Right now it looks like kopf but with a proprietary backend for talking to elasticsearch.

**Comment by gpestana** [comment]
@xrl The next Elasticsearch version (v5) will deprecate the use of site plugins, which is how Kopf is shipped nowadays. So cerebro will allow user to use a kopf-ish standalone monitoring tool for cluster.

More at: 
https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_plugins.html
https://github.com/lmenezes/elasticsearch-kopf/issues/341

**Comment by xrl** [comment]
OK, I see that this is motivated by the removal of site-plugins. On our project we have been very happy with the "official" kopf docker image which uses nginx for the reverse proxying. What are the benefits of the scala-powered backend in cerebro vs. the existing nginx reverse proxy?

**Comment by micw** [comment]
What xrl mentioned is a good point. I'm migrating some es instances from 1.x to 5.x. For head/kopf I simply had to run nginx to serve the static content of the old site plugin. Works perfect. So I wonder a bit why it's required to run another server side component to get the old kopf feratures back.

**Comment by lmenezes** [comment]
hey all

at the moment there are no benefits in using cerebro over kopf. and perhaps depending on your use case, there may never be benefits.

as some of you have noted, kopf can still be used being served by apache/nginx, so if you are happy  with kopf, this should still work for you. i will make sure to find the time to find any compatibility issues that arise.

cerebro on the other hand is born from the needs I currently have and where kopf falls short: an admin tool that handles multiple clusters and where access to these cluster can be controlled through LDAP groups(in both clusters that are accesible and operations, read/write, that are accesible for each of these clusters).

this is of course nowhere near to exist at the moment, and I have no idea when it will be done. but, i will need a proper backend for this. 

so, that's the reasoning behind cerebro :)
