### ISSUE TITLE
what is the difference between cerebro an kopf?

### ISSUE THREAD

**Issue by azulay7** [lmenezes/cerebro#309]

**Comment by RogierSchuring** [comment]
Cerebro works with elasticsearch 5.x and 6.x and kopf doesn't (as far as I know).

Also, Kopf was an elasticsearch plugin and due to changed policy on elastic side, was no longer allowed.
Cerebro is a standalone app.

**Comment by azulay7** [comment]
thanks!! that was helpful :)

**Comment by tle-livongo** [comment]
Actually kopf can work with ES 5.6 and 6.x.  That's what I am using at the moment with ES 6.3.0.

I have a forked version that work for me.

**Comment by moliware** [comment]
The main reason of starting a standalone app was exactly what @RogierSchuring said, elasticsearch doesn't allow plugins like kopf. So, kopf was discontinued and Cerebro was created :)
