### ISSUE TITLE
Cerebro with reverse proxy

### ISSUE THREAD

**Issue by Alexwii** [lmenezes/cerebro#31]
Hello everyone,

I will need Cerebro listen only in localhost, accessible with a reverse proxy and authentication.

How can I doing that ?

Thank you so much for this nice tool.

**Comment by Nefelim4ag** [comment]
You can use any online reverse proxy configuration

Example for Nginx + ldap
```
server {
        listen      80;
        server_name es.itransition.corp;
        return 301 https://$server_name$request_uri;  # enforce https
}

server {
        listen                *:443;
        server_name es.itransition.corp;

        ssl on;
        ssl_certificate         /etc/ssl/private/es.pem;
        ssl_certificate_key     /etc/ssl/private/es.key;

        access_log      /var/log/nginx/es.access.log;

        location / { proxy_pass http://127.0.0.1:9000; }

        auth_ldap "ldap_group";
        auth_ldap_servers ldap_config;
}
```

**Comment by Alexwii** [comment]
Yes ok, but my problem it's Cerebro is not only accessible in localhost, I can join him with with her IP or her DNS and I don't want this. How can I force Cerebro to listen only in 127.0.0.1 in exemple ?

**Comment by lmenezes** [comment]
hey @Alexwii 

I believe you can pass the -Dhttp.address=127.0.0.1 while executing the app.

I haven't yet tested, so let me know if this works so I can add to the readme as this might be useful for others.

**Comment by Alexwii** [comment]
Yes it's ok for me, that's works ! 

Thanks again for this tool :)

**Comment by yuriybash** [comment]
I have a related question:

is putting cerebro behind nginx (or other reverse proxy) a valid or recommended way of blocking potentially destructive (i.e. non-GET) requests from getting to cerebro? i.e., include non-GET blocking in nginx config. 

The use case I'm thinking of is having cerebro running on an instance somewhere, and allowing devs to use it in "read-only" mode, so that they have access to the dashboard, but without the potential of executing potentially harmful actions. I was considering forking cerebro and adding a "read-only" capability, but this seems like a far easier option, if it works?

**Comment by lmenezes** [comment]
Hey Yury,

I don't this would solve much, as the actual requests to ES are done by the backend, as this won't go through the proxy.

On the other hand, this is something that I would like to work on soon(meaning, allowing a read-only cerebro usage). Don't hold your breath, as this won't be available too soon, but hopefully it won't take too long.

**Comment by yuriybash** [comment]
@lmenezes I understand cerebro speaks to ES on the backend, what I was picturing was having a reverse proxy sitting _in front of_ cerebro, to filter non-GET requests - this way, cerebro would never even receive any potentially destructive requests. something along the lines of:

user --> nginx --> cerebro --> elasticsearch

and nginx would have [this](http://nginx.org/en/docs/http/ngx_http_core_module.html#limit_except) type of config set up to take care of the filtering.

thanks for all the work you've done on cerebro, it's incredibly useful!

**Comment by rtkgjacobs** [comment]
I've setup a reverse proxy between cerebro and elasticsearch. Such that a developer can use a 'read only' URL path to work with elasticsearch, but only perform "GET" requests to vastly reduce destructive operations. There are certain things you can still possibly do via GET but not from my tests with the cerebro interface vs the elasticsearch API's (ignoring the rest interface) . YMMV.

The solution stack we deploy with clusters is basically...

nginx ---> Cerebro ---> nginx ---> elasticsearch cluster

Here is an example nginx config that acts as the 'full' or 'read-only' reverse proxy to elastic. I make no claims to warranty, use at your own risk, etc etc.

```
upstream elasticsearch {
    server your_elastic_server_FQDN:9200;
    server your_elastic_server2_FQDN:9200;
    keepalive 15;
}

  server {
    listen 9200;
    server_name "";
    location / {
      proxy_pass http://elasticsearch;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header    Host $host;
      proxy_redirect     off;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /readonly/ {
      if ($request_method !~ "GET") {
        return 403;
        break;
      }
      proxy_pass http://elasticsearch/;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header    Host $host;
      proxy_redirect     off;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

So above hitting the `/readonly` URL path with cerebro, limits to GET operations, and hitting the root path `/` gives full access. We also generate the cerebro 'connections' settings for users so they can select which level of control they want easily.

I've done much more extensive HAProxy API limits with elastic in the past, you can google around for online examples.
