### ISSUE TITLE
Logging of request errors includes username and password in output 

### ISSUE THREAD

**Issue by byroncollins** [lmenezes/cerebro#315]
When connecting to an secured elasticsearch index that is authenticated by basic auth the username and password are being logged to the error log when you get request errors.

```bash
[info] play.api.Play - Application started (Prod)
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[error] application - Error processing request [path: /nodes, body: {"host":"https://elasticsearch-nonprod.ocp.org/","username":"elastic","password":"thepassword"}]
javax.net.ssl.SSLException: SSLEngine closed already
	at play.shaded.ahc.io.netty.handler.ssl.SslHandler.wrap(...)(Unknown Source)
```

We're running cerebro in a container and logging is directed to STDOUT so we see this in our container logs

**Comment by andrewgdotcom** [comment]
Writing plaintext passwords to the logs is catastrophically bad. It appears this is being thrown from app/controllers/BaseController.scala:

```
  private def formatRequest(request: AuthRequest[JsValue]): String = {
    s"path: ${request.uri}, body: ${request.body.toString}"
}
```

This should be replaced by something that censors the password before calling toString(). I don't know Scala well enough to make a patch though.

**Comment by daplho** [comment]
+1

**Comment by krithigaPillai** [comment]
+1

**Comment by anthonyhaussman** [comment]
+1

**Comment by tcristina** [comment]
+1
