### ISSUE TITLE
High load

### ISSUE THREAD

**Issue by SebScoFr** [lmenezes/cerebro#320]
Just wondering, what would explain a high load but very low Heap / CPU usage?

![Cerebro](https://image.ibb.co/eES2Vz/Screen_Shot_2018_08_20_at_16_16_12.png)

**Comment by xiashiwendao** [comment]
I have the same question, what dose load mean?

**Comment by rtkgjacobs** [comment]
You should likely consult with Elastic's own documentation, as Cerebro is just polling each node for these details. I believe this is the source of the data above in your screenshot. You should study that further. 

https://www.elastic.co/guide/en/elasticsearch/reference/6.4/cluster-nodes-stats.html#os-stats

**Comment by warder** [comment]
I think "load"column shows [Load Average](https://en.wikipedia.org/wiki/Load_(computing)) of your servers and this may be not related to Elasticsearch or cerebro.

**Comment by SebScoFr** [comment]
Fair enough. Thanks all for your input, I will investigate further.

**Comment by moliware** [comment]
I close this @SebScoFr . If you still think it is a problem, feel free to reopen it.

**Comment by sethyes** [comment]
I had this same issue with ES 7 - turned out that docker with OpenJDK12 has a bug where it only allocates one core, regardless of how many you have. We got around this by adding the JVM flag: 
`-XX:ActiveProcessorCount=32`

**Comment by ghost** [comment]
On which position you @sethyes added the JVM Flag?
I used cerebro with Docker Compose.
