### ISSUE TITLE
[BUG] When a snapshot name includes `.`, the pulldown icon to do a restore does nothing when clicked

### ISSUE THREAD

**Issue by dlcc** [lmenezes/cerebro#327]
give enough details regarding your cerebro setup:
Standard 0.8.1 pulled from gh. Running on Macbook pro, java 8

include versions for elasticsearch and cerebro
ES 6.2.2, also ES2.3.5 and cerebro 0.8.1

describe steps to reproduce the error, the error itself and expected behaviour:
Create a snapshot with the name `snap-2018.10.18`
Try to restore from using the pulldown icon
Expected behavior: Options slide out to specify and execute restore
Actual behavior: Nothing happens

**Comment by moliware** [comment]
Fixed on #351 

It will be available in the next release

Thanks!
