### ISSUE TITLE
Running cerebro with JAVA 10

### ISSUE THREAD

**Issue by necroline** [lmenezes/cerebro#330]
When trying to run cerebro with Java 10 I have the following error :

The java installation you have is not up to date
requires at least version 1.6+, you have
version 10.0.2

**Comment by Pigau** [comment]
Same problem for me,
it seems that the version comparison is wrong

**Comment by regisoc** [comment]
Same here !

**Comment by regisoc** [comment]
Quick workaround for the moment: edit the `bin/cerebro` file, comment lines:
```bash
# check java version
if [[ ! $no_version_check ]]; then
    java_version_check
fi
```
It screams a little bit after that, but it works.

**Comment by Pigau** [comment]
This issue seem to be the same as this one : #290 
@omega said 

> you can also run it with ./bin/cerebro -no-version-check to skip the version checking

**Comment by moliware** [comment]
Thanks for reporting! Unfortunately this is a play problem so the workaround is the only way to go.

Fortunately we have just done #352 and this  should not be a problem in future releases
