### ISSUE TITLE
bin/cerebro not support jdk 11

### ISSUE THREAD

**Issue by smallmenu** [lmenezes/cerebro#350]
bin/cere  in java_version_check may be have bug when I use OpenJDK 11 and ElasticSearch 6.6.1

java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

then I comment these lines, It works:

`
if [[ ! $no_version_check ]]; then
java_version_check
fi
`

**Comment by wojoj93** [comment]
+

**Comment by moliware** [comment]
If you are using the master branch it should work now. If you are using a specific release then wait until the next release :)

Thank you!

**Comment by moliware** [comment]
In the mean time you can execute cerebro as follows:

`./bin/cerebro -no-version-check`

As described by @omega in #290
