### ISSUE TITLE
No java installations was detected for elasticsearch 7.0  

### ISSUE THREAD

**Issue by deter3** [lmenezes/cerebro#362]
I installed elasticsearch 7.0 on ubuntu 16.04 without OpenJDK installed .  After I start cerebro 0.83, it says "No java installations was detected" . 

My question is how can I get cerebro to use elasticsearch bundled OpenJDK without installation of my own version .

**Comment by deter3** [comment]
i found solution , just add elasticsearch 7.0 jdk folder , which is /usr/share/elasticsearch/jdk/ , to JAVA HOME .

**Comment by moliware** [comment]
Thanks for sharing the solution :)
