### ISSUE TITLE
status of snapshot

### ISSUE THREAD

**Issue by drummerwolli** [lmenezes/cerebro#366]
Currently, you only see the snapshot name in the snapshot overview. but the status can be `IN_PROGRESS`, `FAILED` or `SUCCESS` ... by just showing the snapshot name, I would always assume `SUCCESS` which is wrong. cerebro should display the snapshot status as well in the snapshot list.

`kopf` also had this back then ...

**Comment by bradvido** [comment]
This is one of the things I miss from kopf. It would show the status of the snapshot as well as the indexes inside it.
