### ISSUE TITLE
Bugged load bar

### ISSUE THREAD

**Issue by woqer** [lmenezes/cerebro#38]
Hi,

Node load bar shows nothing (like load zero). I tested this on a cluster with kopf, which actually was showing some load value.

Cerebro Load
![cerebro-load](https://cloud.githubusercontent.com/assets/4426659/20801610/20d4926a-b7af-11e6-92a0-a0b13dd5c0fa.png)

Kopf Load
![kopf-load](https://cloud.githubusercontent.com/assets/4426659/20801637/2d2964d2-b7af-11e6-904b-7e3ed257eadf.png)

**Comment by lmenezes** [comment]
which version of ES are you using?

**Comment by woqer** [comment]
Those screenshots were from ES2. But on ES5 I still see no load. Already checked with X-pack and all nodes have >0 load right now.

**Comment by lmenezes** [comment]
@woqer I don't really have a decent internet connection right now, but tomorrow morning I will push a new release that fixes both issues you reported. thanks for that :)

**Comment by woqer** [comment]
Woah! I didn't expected both fixes so soon :)

Thanks.
