### ISSUE TITLE
Can't reset blocks.read_only_allow_delete to false

### ISSUE THREAD

**Issue by x-0n** [lmenezes/cerebro#382]
The above property has been triggered by low diskspace on my ES data partition. After I fixed the root cause, I wanted to reset my indices using cerebro.

Instead of the expected result, I got an error message:

```
{
  "error": {
    "root_cause": [
      {
        "type": "cluster_block_exception",
        "reason": "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
      }
    ],
    "type": "cluster_block_exception",
    "reason": "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
  },
  "status": 403
}
```

Is this not one of the use cases cerebro is trying to cover? I ended up fixing my indices with a manual curl query, but kibana was also able to reset this property.

**Comment by lmenezes** [comment]
@x-0n Could you tell me ES version, cerebro version, and how did you reset your indices?

**Comment by x-0n** [comment]
ES 6.8.1, cerebro 0.8.3

I ended up running this curl query:

```
curl -XPUT -H "Content-Type: application/json" \
   http://<es-host>:9200/_all/_settings \
     -d '{"index.blocks.read_only_allow_delete": false}'
```

**Comment by lmenezes** [comment]
@x-0n Thanks. I can reproduce the issue and will push a fix soonish :)
