### ISSUE TITLE
Jackson Security

### ISSUE THREAD

**Issue by dimkua** [lmenezes/cerebro#383]
https://github.com/FasterXML/jackson-databind/issues/2334

please upgrade jackson-databind

**Comment by lmenezes** [comment]
@dimkua As this comes from play, as soon as play 2.8 is released I will upgrade to it. This should then fix the Jackson issue.

**Comment by lmenezes** [comment]
@dimkua Thanks for pointing this out :)

**Comment by lmenezes** [comment]
@dimkua Took an awful long time, but I finally updated play and jackson as a transitive dependency. Thanks for reporting :)
