### ISSUE TITLE
Missing shard allocation

### ISSUE THREAD

**Issue by woqer** [lmenezes/cerebro#39]
Hi,

The shard relocation info is missing in Cerebro. Tested on a cluster with Kopf at the moment of shard relocation, also double checked with ES API. Allocation was not showing on Cerebro.

Version=0.3.1
Browser=Firefox 50.0

Cerebro shards screenshot
![cerebro-shards](https://cloud.githubusercontent.com/assets/4426659/20801739/7b88143e-b7af-11e6-84d3-1d61b28d24e8.png)

Kopf shards screenshot
![kopf-shards](https://cloud.githubusercontent.com/assets/4426659/20801746/833bb62c-b7af-11e6-9505-e2c7571f323f.png)

Still, the affected shards were showed on black, so i guess the only missing part is the info on the part showed on the screenshots above.

**Comment by lmenezes** [comment]
@woqer for how long was the relocation going? take into account that this info is refresh every 5s, so, if the cluster recovered before that, you won't ever see this.

I have tested this on both 2.X and 5.X, and all seemed fine. Could you confirm?

**Comment by woqer** [comment]
I think it was relocating for 10 minutes. I just checked Cerebro now, the cell space is smaller. So I guess on the screenshot there was supposed to be showing shard allocation. I am adding some new nodes to the cluster today. Will check it on firefox and chrome and report back the results.

**Comment by lmenezes** [comment]
sure. I will close this for now, but feel free to reopen in case this still seems to be an issue.

**Comment by woqer** [comment]
@lmenezes OK, I just added 7 nodes to my 7 node cluster (now 14), and also exclude the old nodes with `"cluster.routing.allocation.exclude._ip"`. Kibana's x-pack is showing shard activity, es cluster API is showing shard allocation. No sign of it on cerebro, not even after refreshing page.
(PS: cerebro's rest feature worked fine)

**Comment by woqer** [comment]
So, when decommissioning nodes, the unassigned shards message appears. Still, after that, the initializing shards message does not appear neither (same as relocating shards).
