### ISSUE TITLE
How to config jvm params? such as -Xms,-Xmx??

### ISSUE THREAD

**Issue by wujiang41105631** [lmenezes/cerebro#399]

**Comment by KOTRET** [comment]
have you tried to place a file `CEREBRO_config.txt` in the app directory? At least this is what i read from the batch-file...

**Comment by wujiang41105631** [comment]
> have you tried to place a file `CEREBRO_config.txt` in the app directory? At least this is what i read from the batch-file...

thanks,I'll try.

**Comment by moliware** [comment]
Reopen the issue if this wasn't solved. Thank you!
