### ISSUE TITLE
how do i install it

### ISSUE THREAD

**Issue by gilisade** [lmenezes/cerebro#4]
hi
i've downloaded the zip file
extracted the file
now how do i install the plugin ?

**Comment by lmenezes** [comment]
cerebro isn't an elasticsearch plugin, it is a stand alone app. check https://github.com/lmenezes/cerebro#installation for how to run it :)

**Comment by lmenezes** [comment]
it means in the folder with the context of the zip package, there is a folder called bin, and an executable file named cerebro inside of it. you just have to execute it.

**Comment by gilisade** [comment]
i turnes out i downloaded the master zip and it didnt have any bin folder 
now it is working thank you!

**Comment by nikhild-cs** [comment]
the zip on extraction doesn't show bin folder

**Comment by nikhild-cs** [comment]
it also gives an error saying missing plugin.properties file as well
