### ISSUE TITLE
HTTP-413 when creating an index

### ISSUE THREAD

**Issue by thePanz** [lmenezes/cerebro#400]
Can not create an ES index with a (very) large configuration.

Cerebro UI (v0.8.4) is receiving a HTTP-413 response from its own backend `create_index/create` API, when the index configuration is quite large.

Analyzing the network pane, the request made by my browser to the Cerebro's `create_index/create` endpoint has a length of ~110Kb (`Content-Length:110453` header).

**Comment by moliware** [comment]
I think you can increase the max body size of the backend overriding `play.http.parser.maxMemoryBuffer` setting in the `application.conf` as explained [here](https://www.playframework.com/documentation/2.8.x/ScalaBodyParsers#Max-content-length)

I close this issue but feel free to reopen it if you didn't get your issue solved.
