### ISSUE TITLE
Browser window/tab locks up when fetching or viewing documents

### ISSUE THREAD

**Issue by rotzbouw** [lmenezes/cerebro#401]
ES: 7.3.2
Cerebro: 0.8.4
Both deployed as Docker containers in Rancher.

As soon as I click the send button, my browser's window or tab locks up until the results return. For medium to large result sets, the window/tab is irresponsive, i.e. I can't scroll without a huge timeout (seconds to minutes). Reproduced on recent Chromium, Chrome and Firefox versions.
For very small result sets (e.g. one hit for small document), the viewing works fine.

Please let me know if you need more information or how I can help to debug this.

**Comment by lmenezes** [comment]
@rotzbouw Hi. In which section/tab does this happen? Rest?
Also, how big of a result set are we talking about?

**Comment by rotzbouw** [comment]
Hi @lmenezes,
yeah, in Rest but not exclusively there. E.g. if I try to view the settings of one of my indices, and the index contains stopwords (hundreds), my tab will be unresponsive for quite some time.

**Comment by lmenezes** [comment]
@rotzbouw from your network inspector, can you see how big(like in bytes) are the responses returned?

**Comment by artshevtsov** [comment]
I had the same problem and it was fixed by upgrading to version 0.8.5

**Comment by rotzbouw** [comment]
Yup, fixed in 0.8.5. Thanks!
