### ISSUE TITLE
java version conflict

### ISSUE THREAD

**Issue by ChesterZheng** [lmenezes/cerebro#411]
Hello, bro
There is a problem that I restarted cerebro on linux when I changed the "auth" by using "basic" and set "username", "password".

The following message is exception:

! @7dmfpal90 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[RuntimeException: java.lang.UnsupportedClassVersionError: controllers/routes has been compiled by a more
 recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:319)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:243)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:382)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:380)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)

**Comment by ChesterZheng** [comment]
This is my configuration
auth = {
  type: basic
    settings: {
      username = "2ccm-admin"
      password = "1q2w3e4r-zxcv"
    }
}

**Comment by ChesterZheng** [comment]
If I use default configuration, it's successful startup. Could you help me to solve this problem. Thank you.

**Comment by jansieman** [comment]
Hi ChesterZheng,

I had the same issue after upgrading and updating the java version to a higher level solved the problem for me. I did not read the minimum spec but I am now running cerebro on openjdk 1.11.

**Comment by lmenezes** [comment]
@ChesterZheng Hi. Sorry, this was my mistake. One of the releases published used jdk 11 to compile. Upgrading to the latest version should work no problems, although I will soon increase the minimum java requirements to use java 11.
