### ISSUE TITLE
When to support 7. X

### ISSUE THREAD

**Issue by shejianmin** [lmenezes/cerebro#412]
When to support Elasticsearch 7. X

**Comment by lmenezes** [comment]
@shejianmin Hi, did you find any specific issue with ES 7.X? It would be great if you could give me specifics of how things that are not working as expected(including cerebro version, browser and ES version).

**Comment by shejianmin** [comment]
@lmenezes Thank you for your work. I found that there is an exception in the analyze module. Is it related to the adjustment of the mapping doc_type 。
cerebro version: 0.8.4
Elasticsearch version：7.4.2
Chrome version: 78.0.3904.108

`
  Error loading index fields
{
  "error": "JsResultException(errors:List((,List(JsonValidationError(List('properties' is undefined on object: {\"content\":{\"type\":\"text\",\"analyzer\":\"ik_max_word\",\"search_analyzer\":\"ik_smart\"}}),WrappedArray())))))"
}
`

**Comment by shejianmin** [comment]
good job
