### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by pdziok** [lmenezes/cerebro#42]
I'd like to set up my cerebro instance on heroku and make it accessible only via HTTPS.

Plan is to use either request filter or custom http action that will check in config if https enforcing is enabled. For http requests with https enforcing flag enabled it should return 400 saying that HTTPS is required or simply redirect to https

**Comment by lmenezes** [comment]
@pdziok hey there,
I'm not 100% sure I understood what you need/want.

cerebro is at the end a play application, and as such, can be configured in the same way. Could you check https://www.playframework.com/documentation/2.5.x/ConfiguringHttps#ssl-certificates to see if this would cover your needs?

**Comment by zhimsel** [comment]
Alternatively, you could set up nginx as a local proxy with SSL (which I'd recommend over exposing cerebro directly)

**Comment by biro11** [comment]
Hello, I successfully configured Cerebro over https only with play framework configuration inside application.conf:
`play.server.https.keyStore.path = "/path/to/jks"
play.server.https.keyStore.password = "pass"
http.port = "disabled"
https.port = "9000"`
