### ISSUE TITLE
 opening db: './cerebro.db': Permission denied 

### ISSUE THREAD

**Issue by RocherKong** [lmenezes/cerebro#425]
opening db: './cerebro.db': Permission denied  is still exists in version 0.8.5

> Jan 26 22:55:12 Rocher cerebro[5425]: Oops, cannot start the server.
Jan 26 22:55:12 Rocher cerebro[5425]: java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 30001ms.
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
Jan 26 22:55:12 Rocher cerebro[5425]:         at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:57)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:136)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:114)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:129)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.DefaultEvolutionsApi.scripts(EvolutionsApi.scala:94)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.ApplicationEvolutions$.$anonfun$runEvolutions$1(ApplicationEvolutions.scala:177)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.ApplicationEvolutions$.withLock(ApplicationEvolutions.scala:203)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.ApplicationEvolutions$.runEvolutions(ApplicationEvolutions.scala:173)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$1(ApplicationEvolutions.scala:53)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$1$adapted(ApplicationEvolutions.scala:53)
Jan 26 22:55:12 Rocher cerebro[5425]:         at scala.collection.immutable.Stream.foreach(Stream.scala:533)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:53)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:85)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:51)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:50)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:41)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:>
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:>
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:21>
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.Guice.createInjector(Guice.java:87)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.Guice.createInjector(Guice.java:78)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:186)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:139)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.Guice.createInjector(Guice.java:87)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.google.inject.Guice.createInjector(Guice.java:78)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:186)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:139)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.core.server.ProdServerStart$.start(ProdServerStart.scala:57)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.core.server.ProdServerStart$.main(ProdServerStart.scala:29)
Jan 26 22:55:12 Rocher cerebro[5425]:         at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Jan 26 22:55:12 Rocher cerebro[5425]: Caused by: java.sql.SQLException: opening db: './cerebro.db': Permission denied
Jan 26 22:55:12 Rocher cerebro[5425]:         at org.sqlite.core.CoreConnection.open(CoreConnection.java:203)
Jan 26 22:55:12 Rocher cerebro[5425]:         at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
Jan 26 22:55:12 Rocher cerebro[5425]:         at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
Jan 26 22:55:12 Rocher cerebro[5425]:         at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
Jan 26 22:55:12 Rocher cerebro[5425]:         at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
Jan 26 22:55:12 Rocher cerebro[5425]:         at org.sqlite.JDBC.createConnection(JDBC.java:114)
Jan 26 22:55:12 Rocher cerebro[5425]:         at org.sqlite.JDBC.connect(JDBC.java:88)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:119)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
Jan 26 22:55:12 Rocher cerebro[5425]:         at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
Jan 26 22:55:12 Rocher cerebro[5425]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Jan 26 22:55:12 Rocher cerebro[5425]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jan 26 22:55:12 Rocher cerebro[5425]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jan 26 22:55:12 Rocher cerebro[5425]:         at java.lang.Thread.run(Thread.java:748)

**Comment by RocherKong** [comment]
cerebro.service :

> [Unit]
Description=Elasticsearch web admin tool
Requires=network.target

[Service]
Type=simple
WorkingDirectory=/usr/share/cerebro
EnvironmentFile=/etc/default/cerebro
ExecStart=/usr/share/cerebro/bin/cerebro
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=60
SuccessExitStatus=143
TimeoutStopSec=5
User=cerebro
ExecStartPre=/bin/mkdir -p /run/cerebro
ExecStartPre=/bin/chown cerebro:cerebro /run/cerebro
ExecStartPre=/bin/chmod 755 /run/cerebro
PermissionsStartOnly=true
LimitNOFILE=1024

[Install]
WantedBy=multi-user.target

**Comment by Nezisi** [comment]
You'll run the cerebro service as the cerebro user.

chown -R cerebro:root /usr/share/cerebro

should fix this.

Additional note:

RuntimeDirectory=cerebro

Will create a /run/cerebro directory.
No need for ExecStartPre / PermissionsStartOnly.
PermissionsStartOnly is deprecated.

**Comment by RocherKong** [comment]
thank you. I have solved this problem by your suggestion.

**Comment by msproact** [comment]
For system-wide setup – i.e. when installed as Debian or RPM package – I suggest changing the path to the database instead. In `/etc/cerebro/application.conf` change `data.path` to:

`data.path: "/var/lib/cerebro/cerebro.db"`
