### ISSUE TITLE
Add content-type to copied curl command

### ISSUE THREAD

**Issue by lordnynex** [lmenezes/cerebro#426]
https://github.com/lmenezes/cerebro/blob/fd046eeb1466895f56c33ffb11532d3727bdfb5e/src/app/components/rest/controller.js#L86

I stumbled across this issue when using the `cURL` button to craft some update by queries. It would be nice if it added `-H 'content-type: application/json'`.

**Comment by lmenezes** [comment]
@lordnynex 👍 
should be an easy fix, will try to find time this week and push a minor release!
