### ISSUE TITLE
Self Signed keystore

### ISSUE THREAD

**Issue by narayananraman** [lmenezes/cerebro#434]
Hi,

I've been trying to get cerebro to accept my server's RootCA. I have the below in my conf file

play.ws.ssl {
  trustManager = {
    stores = [
      {type = "JKS", path = "/path/to/root_keystore.jks",password="${pass}"}
      {type = "PEM", path = "/path/to/root-ca.pem" }
    ]
  }
}

Tried with either/or keystore/pem and both

Also tried adding the store along with the service initiation command.

./bin/cerebro -Djavax.net.ssl.trustStore=/path/to/root_keystore.jks 

None of the above methods seem to be working. Cerebro is trying to fetch its default self-signed keystore whilst ignoring the provided keystores.

I even tried replacing the selfsigned.keystore with my rootCA keystore but its failing with incorrect password error.

Could someone please help me debug this situation?

**Comment by elkekou** [comment]
Hi,
you can try to register your rootca directly into your default java keystore in RHEL /etc/pki/java/cacerts with  command keytool.

**Comment by moliware** [comment]
If this wasn't solved, please reopen the issue. Thank you
