### ISSUE TITLE
LDAP Configurations

### ISSUE THREAD

**Issue by narayananraman** [lmenezes/cerebro#436]
Hi,

I have successfully configured the LDAP authentication for cerebro. But the problem is all authenticated users have the same amount of access. We have different users with different access levels under the group. But that doesn't seems to make a difference once you are authenticated. 

Is there a provision to differentiate all access users from normal users in Cerebro?

Thanks in advance,
Narayanan Raman

**Comment by elkekou** [comment]
Hi,
For your problem if i do not misunderstand, i think it's normal cerebro does not manage role but only auth. If you want role based authentication you must do it on elasticsearch.

On my side i'm stuck with ldap configuration (https://github.com/lmenezes/cerebro/issues/435)
So perhaps you could share your config? Do you authenticate against openldap or active directory? 
Which directive did you configured?


Thank you ;)

**Comment by moliware** [comment]
Hi!

So far there are no roles for cerebro, just auth as @elkekou said. I can't give you an answer wether we implement something like this in the future. It makes sense but not sure if we will find time for it.

Thank you!
