### ISSUE TITLE
LDAP User template

### ISSUE THREAD

**Issue by narayananraman** [lmenezes/cerebro#440]
Hi,

This is my input to LDAP authorization user = "domain_name\username", which is what I need to authorize the user. Then when I move to user group authentication, I need the domain_name part of the string removed. How do i use "user-attr-template" parameter to format the string to a desired value, which is just "username"?

Any input will be helpful

Thanks,
Narayanan Raman

**Comment by moliware** [comment]
Hi!

Unfortunately it's not possible to remove so, It would be good if the input of the user was just the username. In that case you could configure

- `auth.settings.user-template` (or env var `LDAP_USER_TEMPLATE`): "domain_name\%s"
- `auth.settigs.group-search.user-attr)` (or env var `LDAP_USER_ATTR_TEMPLATE`): "%s"

**Comment by moliware** [comment]
Hopefully what I said helps. Otherwise feel free to reopen the issue.
