### ISSUE TITLE
<Fixed> Unable to get LDAP auth working with group restriction

### ISSUE THREAD

**Issue by trenb** [lmenezes/cerebro#442]
Hi! Running version 0.9.0. I am able to configure Cerebro to authenticate to our AD server just fine, however when I try to add a group membership filter, auth no longer works. I cannot for the life of me find any way to debug this application to find out what's going on. 

Can you recommend any way of adding more debugging to the LDAP client? To be clear, LDAP auth on its own works, but as soon as I try to enable group membership requirements, it stops works, with no errors logged anywhere.

Thanks in advance! Please let me know if you need any more information.

**Comment by trenb** [comment]
Well, looked at it from a different perspective and got it working. Can this be added to the documentation as a working Active Directory implementation?
```
# Authentication
auth = {
  type: ldap
  settings {
    url = "ldap://1.2.3.4:389"
    base-dn = "OU=Staff,DC=your,DC=company"
    method = "simple"
    user-template = "%s@your.company"
    bind-dn = "BINDDN@your.company"
    bind-pw = "BINDPW"
    group-search {
      user-attr = "userPrincipalName"
      user-attr-template = "%s@your.company"
      group = "memberOf=CN=cerebro,OU=Groups,DC=your,DC=company"
    }
  }
}
```
Users will need to adjust values to match their environment.

**Comment by moliware** [comment]
I'll close it as it's fixed. Thank you!
