### ISSUE TITLE
Error loading repositories

### ISSUE THREAD

**Issue by esteban1983cl** [lmenezes/cerebro#444]
Hi, greetings from Chile.
I'm using cerebro for manage my clusters and working perfectly.
Now currently I'm working on manage snapshots in s3 repositories and I found this error when I click on More > Repositories menu option:

`
[error] application - Error processing request [path: /repositories, body: {"host":"Elasticsearch EKS Logging"}]
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(JsonValidationError(List('settings' is undefined on object: {"type":"s3"}),WrappedArray())))))
	at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:25)
	at play.api.libs.json.JsError.fold(JsResult.scala:64)
	at play.api.libs.json.JsReadable.as(JsReadable.scala:24)
	at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
	at play.api.libs.json.JsUndefined.as(JsLookup.scala:181)
`

[https://ibb.co/ZdygBWM](UI Screenshot)

**Comment by lmenezes** [comment]
@esteban1983cl which version of cerebro are you using? this got fixed on v0.9.0 (although I just released v0.9.1, so you might want to get that)

**Comment by zhixiangjoy** [comment]
I meet the same probelm ,and also I can't add respositories!
