### ISSUE TITLE
'attributes' is undefined on object

### ISSUE THREAD

**Issue by jacobreid** [lmenezes/cerebro#448]
I have Cerebro running for AWS ElasticSearch clusters via aws-signing-proxy (https://github.com/cllunsford/aws-signing-proxy). Today I started getting errors when viewing the overview and nodes pages (the REST client seems to still work, as well as functionality like index templates). In the container logs, I have this error:

`[[31merror[0m] application - Error processing request [path: /nodes, body: {"host":"AWS ES development"}]
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(JsonValidationError(List('attributes' is undefined on object: {"name":"UmewAJY","version":"6.8.0","build_flavor":"oss","build_type":"tar","build_hash":"dadef69","roles":["master"],"os":{"refresh_interval":"1s","refresh_interval_in_millis":1000,"available_processors":2,"allocated_processors":2},"jvm":{"pid":11308,"start_time":"2020-05-13T20:52:10.539Z","start_time_in_millis":1589403130539,"mem":{"heap_init":"5gb","heap_init_in_bytes":5368709120,"heap_max":"4.9gb","heap_max_in_bytes":5351276544,"non_heap_init":"2.4mb","non_heap_init_in_bytes":2555904,"non_heap_max":"0b","non_heap_max_in_bytes":0,"direct_max":"4.9gb","direct_max_in_bytes":5351276544},"using_compressed_ordinary_object_pointers":"true"}}),WrappedArray())))))
	at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:25)
	at play.api.libs.json.JsError.fold(JsResult.scala:66)
	at play.api.libs.json.JsReadable.as(JsReadable.scala:24)
	at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
	at play.api.libs.json.JsUndefined.as(JsLookup.scala:193)
[[31merror[0m] application - Error processing request [path: /overview, body: {"host":"AWS ES development"}]
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(JsonValidationError(List('attributes' is undefined on object: {"name":"BL57Tf5","version":"6.8.0","build_flavor":"oss","build_type":"tar","build_hash":"dadef69","roles":["master"],"os":{"refresh_interval":"1s","refresh_interval_in_millis":1000,"available_processors":2,"allocated_processors":2},"jvm":{"pid":11441,"start_time":"2020-05-13T20:52:13.535Z","start_time_in_millis":1589403133535,"mem":{"heap_init":"5gb","heap_init_in_bytes":5368709120,"heap_max":"4.9gb","heap_max_in_bytes":5351276544,"non_heap_init":"2.4mb","non_heap_init_in_bytes":2555904,"non_heap_max":"0b","non_heap_max_in_bytes":0,"direct_max":"4.9gb","direct_max_in_bytes":5351276544},"using_compressed_ordinary_object_pointers":"true"}}),WrappedArray())))))
	at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:25)
	at play.api.libs.json.JsError.fold(JsResult.scala:66)
	at play.api.libs.json.JsReadable.as(JsReadable.scala:24)
	at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
	at play.api.libs.json.JsUndefined.as(JsLookup.scala:193)`

**Comment by nono-gdv** [comment]
This is not specific to AWS, I get the same error on a local cluster after upgrading Cerebro to 0.9.1. Version 0.8.3 works fine on the same cluster.

**Comment by jacobreid** [comment]
Dropping the version to 0.8.3 fixed it for me too.

What API calls are made for the overview and nodes pages? Happy to post the output from my AWS clusters for debugging purposes.

**Comment by jgb** [comment]
I've got the same bug I think: my cerebro setup worked fine on v0.9.0 but when I upgraded to v0.9.1 this "attributes is undefined" error message started. I am not using AWS however, I am on elasticsearch v5.6.16

**Comment by Finu** [comment]
Same here - reverting to 0.9.0

**Comment by Silas-91** [comment]
Hi,
at version 0.9.1 i got the error message "Error while loading nodes data". 
<img width="1679" alt="Bildschirmfoto 2020-05-26 um 16 38 04" src="https://user-images.githubusercontent.com/64773536/82914464-d4e22c80-9f6f-11ea-87e9-4b24dcbac507.png">

<img width="1308" alt="Bildschirmfoto 2020-05-26 um 16 37 52" src="https://user-images.githubusercontent.com/64773536/82914693-1d99e580-9f70-11ea-9f43-ff3e527ba5fb.png">

When i use version 0.9.0 i dont have such error messages and everythind works fine. 
<img width="1645" alt="Bildschirmfoto 2020-05-26 um 16 37 06" src="https://user-images.githubusercontent.com/64773536/82914894-576aec00-9f70-11ea-8f8d-96f425c606b5.png">

So i think there is a problem in version 0.9.1.

**Comment by vmercierfr** [comment]
https://github.com/lmenezes/cerebro/commit/1af8da1142f5b6cc98d4ef9bf057c0341fbc6540#diff-560d6b2470c110252b90f947d1d8a53f introduced `attributes` fields but sounds like this parameter does not exists.

We have similar error on `/overview` endpoint since `0.9.1` version, we tested on:
- Elasticsearch 6.2.3 on AWS cloud
- Elasticsearch 7.6.2 on Elastico cloud
