### ISSUE TITLE
is there anyway to avoid inputting Node address manually when access ES cluster?

### ISSUE THREAD

**Issue by huangyonghome** [lmenezes/cerebro#450]
I think it is unreasonable to input node address manually every time when I access Cerebro .
it there anyway to skip that step and get the ES cluster status straightly ?

**Comment by lmenezes** [comment]
@huangyonghome You can always simply use the URL http://localhost:9000/#/overview?host=http:%2F%2Flocalhost:9200

This will skip the connection screen and hop directly to the overview page. Something that has been asked for in the past is that, if there is a single known cluster configured, that cerebro connects to it directly (which I guess makes sense). If I find enough time to work on it I will keep this in mind, as it should not be too much work.
