### ISSUE TITLE
Seems cerebro doesn't work with es 6.1.4 and 6.8.6

### ISSUE THREAD

**Issue by marcofranssen** [lmenezes/cerebro#453]
I have been trying Cerebro on following elasticsearch versions (`6.1.4` and `6.8.6`) using docker-compose.

In both cases I get following error. See further below for my setup.

```
cerebro_1        | [error] application - Error processing request [path: /overview, body: {"host":"Grimoirlab"}]
cerebro_1        | play.api.libs.json.JsResultException: JsResultException(errors:List((,List(JsonValidationError(List('attributes' is undefined on object: {"name":"STF46FE","transport_address":"192.168.208.3:9300","host":"192.168.208.3","ip":"192.168.208.3","version":"6.1.4","build_hash":"d838f2d","roles":["master","data","ingest"],"os":{"refresh_interval":"1s","refresh_interval_in_millis":1000,"name":"Linux","arch":"amd64","version":"4.19.76-linuxkit","available_processors":4,"allocated_processors":4},"jvm":{"pid":1,"version":"1.8.0_161","vm_name":"OpenJDK 64-Bit Server VM","vm_version":"25.161-b14","vm_vendor":"Oracle Corporation","start_time":"2020-06-02T12:24:14.356Z","start_time_in_millis":1591100654356,"mem":{"heap_init":"1gb","heap_init_in_bytes":1073741824,"heap_max":"990.7mb","heap_max_in_bytes":1038876672,"non_heap_init":"2.4mb","non_heap_init_in_bytes":2555904,"non_heap_max":"0b","non_heap_max_in_bytes":0,"direct_max":"990.7mb","direct_max_in_bytes":1038876672},"gc_collectors":["ParNew","ConcurrentMarkSweep"],"memory_pools":["Code Cache","Metaspace","Compressed Class Space","Par Eden Space","Par Survivor Space","CMS Old Gen"],"using_compressed_ordinary_object_pointers":"true","input_arguments":["-Xms1g","-Xmx1g","-XX:+UseConcMarkSweepGC","-XX:CMSInitiatingOccupancyFraction=75","-XX:+UseCMSInitiatingOccupancyOnly","-XX:+AlwaysPreTouch","-Xss1m","-Djava.awt.headless=true","-Dfile.encoding=UTF-8","-Djna.nosys=true","-XX:-OmitStackTraceInFastThrow","-Dio.netty.noUnsafe=true","-Dio.netty.noKeySetOptimization=true","-Dio.netty.recycler.maxCapacityPerThread=0","-Dlog4j.shutdownHookEnabled=false","-Dlog4j2.disable.jmx=true","-XX:+HeapDumpOnOutOfMemoryError","-Des.cgroups.hierarchy.override=/","-Des.path.home=/usr/share/elasticsearch","-Des.path.conf=/usr/share/elasticsearch/config"]}}),WrappedArray())))))
cerebro_1        | 	at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:25)
cerebro_1        | 	at play.api.libs.json.JsError.fold(JsResult.scala:66)
cerebro_1        | 	at play.api.libs.json.JsReadable.as(JsReadable.scala:24)
cerebro_1        | 	at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
cerebro_1        | 	at play.api.libs.json.JsUndefined.as(JsLookup.scala:193)
```

```yaml
version: '3.7'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.4"
    ports:
      - "9200:9200"
      - "9300:9300"

  cerebro:
    image: lmenezes/cerebro:0.9.1
    ports:
      - "9000:9000"
    depends_on:
      - elasticsearch
```

I'm connecting cerebro to `http://elasticsearch:9200`. In the UI it shows error while loading data. On the network tab of the browser all requests succeed with an HTTP 200 response.

**Comment by marcofranssen** [comment]
@lmenezes is es 6.x supported by cerebro? Any leads we can add to the ticket on how to resolve? Maybe someone with Scala experience in the community will then be able to support.

**Comment by avdv** [comment]
@marcofranssen this seems to be the same issue as #448 , try to downgrade to 0.9.0

**Comment by marcofranssen** [comment]
@avdv 0.9.0 gives the following error. 

```cerebro_1        | WARNING: An illegal reflective access operation has occurred
cerebro_1        | WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/opt/cerebro/lib/com.google.inject.guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
cerebro_1        | WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
cerebro_1        | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
cerebro_1        | WARNING: All illegal access operations will be denied in a future release
```

**Comment by marcofranssen** [comment]
@avdv 0.8.5 gives same warnings, but then successfully starts and works.

**Comment by avdv** [comment]
> @avdv 0.9.0 gives the following error. 
> 
> ```cerebro_1        | WARNING: An illegal reflective access operation has occurred
> cerebro_1        | WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/opt/cerebro/lib/com.google.inject.guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> cerebro_1        | WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
> cerebro_1        | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> cerebro_1        | WARNING: All illegal access operations will be denied in a future release
> ```
> 
> After that no logs and doesn't come up on localhost:9000

These are just warnings and should not cause any problems.

**Comment by pulkitsethi** [comment]
Another data point: 0.9.0 works for me. 0.9.1 is having the issue described.

ES version: 6.3 (AWS managed cluster)

**Comment by lmenezes** [comment]
Hey, sorry for the long delay. Cerebro should work without problems with ES 6/7. I assume all of you are running AWS managed ES? I know the AWS managed APIs are not strictly the same as plain vanilla ES.

**Comment by avdv** [comment]
If this is indeed the same problem as #448, then 0.9.2 should fix this right?!

**Comment by marcofranssen** [comment]
I haven't tried it yet. But I was using this docker-compose setup with 6.8.6 version of elasticsearch. In this blog I used version 0.8.5 in combination with elasticsearch 7.7.

https://marcofranssen.nl/building-a-elasticsearch-cluster-using-docker-compose-and-traefik/

So I wasn't using a AWS ES version.

**Comment by lmenezes** [comment]
@marcofranssen Sorry, I misjudged earlier and thought it was a AWS related issue, which wasn't. Still, 0.9.2 should fix this :)
