### ISSUE TITLE
Elasticsearch with authentication ( Cerebro Helm)

### ISSUE THREAD

**Issue by danilorsilva** [lmenezes/cerebro#466]
Hello all,

     Is there a way to set user and password on cerebro installation using helm?

     https://github.com/helm/charts/tree/master/stable/cerebro

     I only find this options:

          config:
            basePath: '/'
            restHistorySize: 50
            hosts: []
            #  - host:
            #    name:

     Thanks!

**Comment by moliware** [comment]
Hi!

I don't know much about helm but if you could add environment variables  then you could have basic authentication (user: `admin` / password: `admin`) by exporting:

```
- AUTH_TYPE=basic
- BASIC_AUTH_USER=admin
- BASIC_AUTH_PWD=admin
```

**Comment by zeph** [comment]
putting a note just to remember to look at this... I can help @moliware 
but I need first to create a ticket to save the helm chart... cause it will be phased out from charts.helm.sh
