### ISSUE TITLE
Cerebro wont load overview if cluster is big

### ISSUE THREAD

**Issue by D4NNYX** [lmenezes/cerebro#467]
Hello there,

Im trying to connect Cerebro to my 10TB ElasticSearch cluster, but without success. Request is pending on /overview, which after some time timeouts.

I checked all endpoints in app/elastic/HTTPElasticClient.scala, but all of them was completed after few seconds, could you please help me with this problem?

Thanks you in advance.

**Comment by mhoydis13** [comment]
Same issue here.  Success with smaller clusters, larger clusters with many member instances of elasticsearch seems to hit some timeout somewhere,  but I'm not sure where.  
I am upgrading to 0.9.2 and am hitting this issue.  Version 0.7.2 seems to play nicer with the larger clusters.

**Comment by xiaowushen** [comment]
i have same question

**Comment by cjx-great** [comment]
i also have same question

**Comment by moliware** [comment]
Hi @D4NNYX ,

I would need more information to debug the problem. i.e:

- version
- how many indices
- Equivalent request executed against elasticsearch takes also few seconds? 

Thinking about possible problems I wonder if:

- Elasticsearch is slow then cerebro will be slow and we can do nothing.
- Elasticsearch is fast but API part of cerebro is slow
- UI is slow because there are too many items to show

**Comment by lmenezes** [comment]
It would actually be great if you could provide a script that creates all indices in your cluster. Field names, index names and etc are not important, but the amount of them and the sharding setup are. If you could also tell us how many nodes, we might be able to debug this.

**Comment by D4NNYX** [comment]
Cerebro 
v0.9.2

ElasticSearch
v7.8.0
8643 indices 
17116 shards (most of indices have 1 shard)
1 replica for all indices
3 master, 12 data, 2 coordinate nodes

I dont have a script which create all the indices, Elastic is part of Elastic Stack, so Logstash is the component which creates indices dynamically.

**Comment by xiaowushen** [comment]
Hello @moliware, @lmenezes ,
here are my information:

cerebro version : v0.9.2
elasticseach version: 7.5.1
indices in cluster: 10835(5541 indices open , 5346 indices close)
nodes in cluster: 29nodes
total shards: 38211
total docs: 43 105 545 558
total size: 12.26 TB

I download source code find overview request cluster state,nodes stats,stats docs,cluster settings,aliases,cluster health、nodes jvm, it takes a few seconds, by debugging source code I find it pending at app/models/overview/clusterOverview.scala line 53.
![image](https://user-images.githubusercontent.com/23205470/92102755-94693900-ee11-11ea-9fe8-4b1a6c6ab559.png)

Through debugging I think property blocks only contain index close, blocks get index open not in json obj will take lots of times, so I change this, now is worked well.
![image](https://user-images.githubusercontent.com/23205470/92111420-d9479c80-ee1e-11ea-9702-fd30b183002b.png)

**Comment by moliware** [comment]
Good catch @xiaowushen . I investigated a bit further and in the following scenario:

- A big number of indices
- Many of the indices are closed 

this line becomes a bottleneck:

```val indexStats   = (indicesStats \ "indices" \ index).asOpt[JsObject].getOrElse(Json.obj())```

Being `indicesStats` a big json object, when doing the lookup to find `index` and this `index` is closed (then the lookup fails) the json library construct a string with the full json (https://github.com/playframework/play-json/blob/2eb4900/play-json/shared/src/main/scala/play/api/libs/json/JsLookup.scala#L107). Doing this for each closed index ruins the performance.

I will prepare a fix to be released in the next version.

Thank you!
