### ISSUE TITLE
Fatal error in starting the Cerebro

### ISSUE THREAD

**Issue by garihogar** [lmenezes/cerebro#472]
When I start Cerebro, it reports the following error:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/cerebro/lib/com.google.inject.guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] play.api.Play - Application started (Prod) (no global state)
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

I`ve Elasticsearch 7.8 and JDK 11

**Comment by moliware** [comment]
Hi!

Those are warnings messages, but cerebro works fine even though it display those messages. It's inconvenient but it's how it is right now.

Sorry!
