### ISSUE TITLE
Support custom location

### ISSUE THREAD

**Issue by kayrus** [lmenezes/cerebro#48]
I'd like to use cerebro under custom location, i.e. `/cerebro`.

I have configured nginx to proxy-pass requests from `/cerebro` to `cerebro` upstream, but it doesn't support custom locations and tries to fetch hosts using root location: `/connect/hosts`

P.S. Custom `routes` file doesn't help.

**Comment by Nefelim4ag** [comment]
+1

**Comment by xiaocen2050** [comment]
+1

**Comment by joaquinvanschoren** [comment]
+1

**Comment by jockjiang** [comment]
+1.  I also like this feature.

**Comment by kayrus** [comment]
@lmenezes any progress on this issue?

**Comment by lmenezes** [comment]
@kayrus not as of now, sorry. I'm currently finishing adding auth support(LDAP/username&password),and this could be next on the list.

**Comment by michalmiddleton** [comment]
+1

**Comment by speedplane** [comment]
I'd like to see this feature as well, it's similar to kibana's `server.basePath` feature. Instead, as a workaround, I'm using the following NGINX configuration. The first line has to catch all potential cerebro URLs, without messing up elasticsearch (hosted on the same server). It's pretty darn ugly:

```
location ~ ^/(cerebro|templates|overview|mode-json.js|theme-cerebro.js|snapshots$|public/fonts/fontawesome\-|cluster_changes|cluster_settings|repositories|navbar|connect/hosts|commons/indices|aliases/get_aliases) {
        proxy_pass http://localhost:9000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite ^/cerebro/(.*)$ /$1 break;
        
        # Do not redirect, otherwise we'll need to set letsencrypt here too.
        auth_basic "Elasticsearch Authentication";
        # This file will be generated in the startup script.
        auth_basic_user_file /elasticsearch/config/user.pwd;
    }
```

**Comment by champtar** [comment]
Hi all, please test #85

**Comment by zhenwenc** [comment]
Hi all, its been quite a while, any update on this?
