### ISSUE TITLE
平台能否新增管理员和普通使用者的功能

### ISSUE THREAD

**Issue by huangpeng0817** [lmenezes/cerebro#502]
能否开发管理员权限和普通权限功能，管理员目前所有操作。普通的只能有查看索引，mappng，等不能修改集群配置和索引，在rest中只能GET。目前同一套平台，管理和开发使用，都只能用管理员账号，权限太大了

**Comment by moliware** [comment]
After using google translate, I'm closing because this is something similar to:
- https://github.com/lmenezes/cerebro/issues/403
- https://github.com/lmenezes/cerebro/issues/275

The idea is good, but there is no plan to develop admin/user roles or a read only mode for now.
