### ISSUE TITLE
noone of non-data nodes shows in gui

### ISSUE THREAD

**Issue by ignaqui** [lmenezes/cerebro#51]
Hello,

Awesome product, like it so much (used kopf on ES 4.x previously). Thanks for great job!
I'd like to clarify one thing. My cluster consists of 4 nodes: 3 data, and 1 ingest. So, on the top, I can see my cluster name and correct number of nodes (4). However, in the bottom part I see only data nodes.
Is this a bug or a feature?

elasticsearch 5.1.1, cerebro 0.4.1

Sincerely,
ignaqui

**Comment by Tonyko** [comment]
check #29

**Comment by ignaqui** [comment]
Thanks!
