### ISSUE TITLE
How can I specify non-default configuration file to use?

### ISSUE THREAD

**Issue by ayashjorden** [lmenezes/cerebro#53]
Hello,
Let me first say that Cerebro is great :) much like KOPF.

Cerebro help (-h) doesn't include this option, is it part of Play framework configuration?

Thank you,
Yarden

**Comment by ayashjorden** [comment]
Hi @lmenezes,
I've found it in Play2 documentation, its the `-Dconfig.resource` property.

I think that it should go into both README.md and bin/cerebro, WDYT?

**Comment by dylanmei** [comment]
You can also set every property you need via the command-line. For example: `-Dhosts.0.host=http://localhost:9200`

**Comment by lmenezes** [comment]
@ayashjorden sure, I can add this 👍

**Comment by ayashjorden** [comment]
@lmenezes , there's a typo in line [52](https://github.com/lmenezes/cerebro/commit/f3ee2416f83bb84f4d7f6d3863d8986878a974bc#diff-04c6e90faac2675aa89e2176d2eec7d8R52), should be `-Dconfig.*file*`
