### ISSUE TITLE
How can I totally disable auth?

### ISSUE THREAD

**Issue by movsb** [lmenezes/cerebro#553]
Hi, my Cerebro is behind a proxy and is secured by a gateway. So I want to totally disable the default Cerebro auth (by default either LDAP or Basic) and use the common auth provided by the gateway.  I've tried to set auth to Basic type and leave the username and password empty, but it still asks me to input a username and password.

I tried to post the `username` and `password` as form-data to `/auth/login`, it seemed to work. But it's kind of tricky.

Thank you.

**Comment by tommygarvin** [comment]
Hi, @movsb .  You should be able to achieve what you're looking for by leaving `application.conf` [authentication section](https://github.com/lmenezes/cerebro/blob/ccb60448b030ead90cb7309221e296c8da920175/conf/application.conf#L29-L67) as-is and not configuring either basic or ldap.

**Comment by movsb** [comment]
@tommygarvin  Oops! Works as expected, thank you so much. 😅

Maybe the comment of `auth.type` in the `application.conf` should be updated.
