### ISSUE TITLE
Bind to IP

### ISSUE THREAD

**Issue by ceeeekay** [lmenezes/cerebro#56]
Is there any config option to get Cerebro to bind to a specific IP? Alternatively can I request this as a feature? It would be a great help.

Thanks!

**Comment by lmenezes** [comment]
hey,
unless i don't understand what you need, this should already be possible:

(from the docs)
```
HTTP server address and port

You can run cerebro listening on a different port(9000) and host(0.0.0.0):

bin/cerebro -Dhttp.port=1234 -Dhttp.address=127.0.0.1
```

**Comment by ceeeekay** [comment]
Oh, I'm sorry. I was looking in the config and not the docs. :(

That's perfect, thanks.
