### ISSUE TITLE
Naming hosts in application.conf

### ISSUE THREAD

**Issue by dekhtyarev** [lmenezes/cerebro#58]
Hello! 

Thanks for your product!

Question - whether it is possible to specify the host names which are described in application.conf?
Example:
```
...
hosts = [
  {
    name = "ES Production"
    host = "http://ip1:9200"
  }
  {
    name = "ES Staging"
    host = "http://ip2:9200"
  }
]
...
```
In order to `name`, replacement `host` in the web interface.

If this is not implemented - you can to consider this issue, as a feature request :)

**Comment by lmenezes** [comment]
@dekhtyarev this is not yet implemented, but it is planned to. hopefully for next release this will be avaialble :)

**Comment by dekhtyarev** [comment]
Thanks!
