### ISSUE TITLE
overview not working on 0.5.0 + Elastic 5.1.1

### ISSUE THREAD

**Issue by jalberto** [lmenezes/cerebro#59]
it does work on 0.4.2 but not in 0.5.0 I cannot see any relevant error in log, overview is just empty

**Comment by lmenezes** [comment]
can you check on the network inspector in your browser which requests are being sent to the server, and if any of them is failing? if not, could you copy+paste the content of these responses?

I just downloaded both cerebro+es, and all seem to work fine.

Do you change any of the default settings?

**Comment by yannart** [comment]
Have you tried to clear the browser's cache?

**Comment by michalmiddleton** [comment]
@jalberto Clean browser cache (or test in privacy mode). I had the same issue.
