### ISSUE TITLE
Can't connect to ES via SSL

### ISSUE THREAD

**Issue by jochs** [lmenezes/cerebro#6]
Attempting to connect to an ES endpoint protected by jetty auth after setting custom ssl settings results in a 500 error

![screen shot 2016-09-08 at 11 08 54 am](https://cloud.githubusercontent.com/assets/1812645/18355318/bb954ee2-75b6-11e6-8af6-8ec1e1619a39.png)

I had added the following to my `application.conf`

```
play.ws.ssl {
  trustManager = {
     stores = [
      { path: /path/to/jks }     # Added trust store
      { path: /usr/java/jdk1.8.0_45/jre/lib/security/cacerts } # Fallback to default JSSE trust store
     ]
  }
}
```

There is nothing in the `application.log` file when the 500 errors get thown

Removing the above section from the `application.conf` allowed me to connect to endpoints over http, but I continue to get 500 errors. This time, at least, they're related to SSL:

```
play.api.UnexpectedException: Unexpected exception[ConnectException: General SSLEngine problem]
```

**Comment by jochs** [comment]
Note that after setting the custom ssl settings I couldn't connect to _any_ ES endpoint, including the one on localhost.

**Comment by lmenezes** [comment]
@jochs hey
I haven't yet aimed for supporting the setup with SSL, and might be sometime before I actually do. Will keep this in mind though :)

**Comment by jswhitaker** [comment]
Out of curiosity is implementing SSL on your roadmap currently?

**Comment by lmenezes** [comment]
@jochs @jswhitaker so, I finally found time to look into this issue. 

I have just setup a ES node with SSL, and added this to the application.conf:

```
play.ws.ssl {
  trustManager = {
    stores = [
      { type = "PEM", path = "/Users/leo/ca.crt" }
    ]
  }
}
```

After this, I just connected to the server using https, and everything worked out fine. Not sure if your problem could have been because of missing to specify "type", but it would be cool if you could try it again with the latest version and let me know how this goes.

**Comment by lmenezes** [comment]
@jochs @jswhitaker is this still an issue?

**Comment by jswhitaker** [comment]
I have not had a chance to try this out yet. I am hoping to retry using the certificate in the next week.

**Comment by dangetzke** [comment]
I can verify this works fantastic!!! Thanks for adding this, been waiting for the day I can get the ol' kopf - er - cerebro going again. Managing ES just isn't the same without it :)

**Comment by jockjiang** [comment]
it works for me, too. thanks.
