### ISSUE TITLE
Questions about node ordering in overview.

### ISSUE THREAD

**Issue by AtrumOrbis** [lmenezes/cerebro#62]
What's the criteria for node ordering? I have a two node stack that keeps arranging itself constantly (e.g., node1-master will be on top, then on bottom, then on top). I don't see anything else out of the ordinary going on. All resource usage is small. All states are green. All shards are started. Nothing is allocating (turned all allocation off to be sure). There are only 3 indices (special ones), each with 1 shard and 1 replica. I've had it filled to gigs of test data and it does the same thing. My other, 8 node stack doesn't do this. Any ideas?

**Comment by lmenezes** [comment]
@AtrumOrbis There was no criteria, other than the ordering returned by the ES api. As this seems to not always be consistent, I will force sorting on the client side.
