### ISSUE TITLE
Add an install step to change the secret key 

### ISSUE THREAD

**Issue by adamdecaf** [lmenezes/cerebro#65]
The Play! framework requires changing of `play.crypto.secret` from the default value `changeme`. I pulled down version `0.5.0` of this project and was able to run `bin/cerebro` and load the login page at `localhost:9000`. I expected Play! to throw an error telling me to change the default secret. 

I'm not too familiar with Play!, but it seems `application.secret` is [the old value](https://www.playframework.com/documentation/1.0.1/production) for the initial signing param. Does play fallback `play.crypto.secret` and read `application.secret`? 

Either way. I think a step in the install directions needs to mention changing the secret key and the default value in this app needs to be changed to something that won't allow booting of the app. Having this application boot with a publicly shared "secret" allows cookies to be signed by other parties than cerebro. 

https://www.playframework.com/documentation/2.5.x/ApplicationSecret
https://github.com/lmenezes/cerebro/blob/master/conf/application.conf#L8

**Comment by dylanmei** [comment]
Best practices != requirements. Consider adding a note [to the configuration section](https://github.com/lmenezes/cerebro#configuration) of the README.
