### ISSUE TITLE
LDAP User filter

### ISSUE THREAD

**Issue by pbmsys** [lmenezes/cerebro#66]
Hi.
anyone having success with creating a "memberof" user filter?

> auth {
>  type: ldap
>     settings: {
>       url = "ldap://theldapserver.local:389"
>       base-dn = "DC=somedomain,DC=local"
>       method  = "simple"
>       user-domain = "somedomain"
>       user.search.filter = "(|(sAMAccountName=*)(memberOf=SomeGroup,OU=SomeOU,DC=somedomain,DC=local))"
>  }
>     }

Thanks in advance

**Comment by jockjiang** [comment]
Is there any document on how to setup this?

**Comment by pbmsys** [comment]
@jockjiang Not that i could find. Just used normal LDAP syntax.

**Comment by lmenezes** [comment]
@pbmsys no, this is not yet supported, sorry. If you would be willing to contribute though, I would merge it :)

**Comment by johnjoepo** [comment]
May you look at #154
