### ISSUE TITLE
Certificate Authority or Validity of SSL certificates

### ISSUE THREAD

**Issue by sundarv85** [lmenezes/cerebro#71]
Hello,

I'm looking for the option to either provide the CA file or set the SSL certificate validation to be switched off. Something like what Kibana provides

```
# Optional setting that enables you to specify a path to the PEM file for the certificate
# authority for your Elasticsearch instance.
# elasticsearch.ssl.ca: /path/to/your/CA.pem

# To disregard the validity of SSL certificates, change this setting's value to false.
#elasticsearch.ssl.verify: true
```

This is because, we are trying to connect to a self signed ES exposed only through https.

And of course, we loved kopf and with ES 5.x, we want to use with cerebro 👍

**Comment by fizerkhan** [comment]
+1

**Comment by dachenbach** [comment]
+1

**Comment by sundarv85** [comment]
Thanks. This works for now. It would be of course good, if we can also pass the ca.pem file in application.conf
