### ISSUE TITLE
generic question about cerebro

### ISSUE THREAD

**Issue by webedem** [lmenezes/cerebro#72]
great work. i find it extremely useful and even better than other ui tools for ES. Is this a personal project maintained by you or is it a part of a company?

**Comment by lmenezes** [comment]
@webedem hey, this is just a personal project i do on my free time, there is no company behind it :)

**Comment by webedem** [comment]
that's great. do you have a website for cerebro? I'd love to see this  on producthunt

**Comment by lmenezes** [comment]
@webedem no, I don't really have anything other than the github page, which itself isn't even that polished. I have very limited time currently, and try to focus on getting features I consider important out the door more than on "selling" the project(not that I have problems with that). But thanks for the support :)

**Comment by webedem** [comment]
u r probably right. nevertheless, if you ever build a website and want to promote the product, I would love to hunt this on Producthunt so users can see how cool this is
