### ISSUE TITLE
high GC overhead

### ISSUE THREAD

**Issue by afrozl** [lmenezes/cerebro#73]
I wonder if I have something mis-configured. When I start cerebro I almost immediately get messages about high GC overhead in the elasticsearch logs. The overhead increases to the point where the JVM is spending all its time on garbage collection. 

I can reproduce this very easily as all it takes is for cerbro to be started.

**Comment by lmenezes** [comment]
@afrozl hey. how big is your cluster? how many nodes? how many indices? could you share the response of the calls made by the app?(from the network tab on your browser).

**Comment by gfdsa** [comment]
6 nodes
1490 indices
29k shards
as soon as cerebro is started the victim node starts to GC like crazy
every 2-3 seconds a log message about the overhead in the node's elastic.log on info level (25% of jvm time in GC) 
any suggestions?

**Comment by lmenezes** [comment]
@gfdsa not at the moment, sorry. There is another open ticket for this exact issue happening on large clusters(well, not really large clusters, but just lots of indices/shards)

**Comment by gfdsa** [comment]
@lmenezes I see, care to point me to the open one so I can follow? Thanks!
