### ISSUE TITLE
how to execute the program?

### ISSUE THREAD

**Issue by multivac2x** [lmenezes/cerebro#77]
In the instructions is mentioned that we should run the executables from bin/cerebro (or .bat) but I do not see any executable.

Any advice?

**Comment by Tonyko** [comment]
Did you download [release](https://github.com/lmenezes/cerebro/releases/download/v0.5.1/cerebro-0.5.1.zip)?

**Comment by multivac2x** [comment]
Yes thanks. I was getting directly from the sources.
