### ISSUE TITLE
no field name listed of function analysis

### ISSUE THREAD

**Issue by bsc2xp** [lmenezes/cerebro#79]
hi, cerebro is a great project.
I find there is no value listed in the field name selection control  when I choice a index  by the analysis function , is it a bug ? 

can someone help me ? thanks

**Comment by lmenezes** [comment]
have you selected an index? and does this index has a mapping?

**Comment by lmenezes** [comment]
As this seems to work fine for me/others, I will close it for now. If this is still a problem, let me know.
