### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by yannart** [lmenezes/cerebro#8]
Hi,

Great project!

For my own needs I built a Docker image to run cerebro with a docker-compose project example to run it with a cluster of a couple Elasticsearch 5 nodes: https://github.com/yannart/docker-cerebro

Perhaps you'd like to merge it to your project? Or if you prefer to keep it separate I volunteer to maintain the Docker image if you do not have already another.

Regards,

Yann

**Comment by jmwilkinson** [comment]
Maybe this will be merged if you create a pull request?

**Comment by wolfgang-werner** [comment]
+1 please create pull request to get this merged as soon as possible!

**Comment by gianrubio** [comment]
@lmenezes please provide a docker image

**Comment by adarnimrod** [comment]
Created #255 to help provide official Docker images.

**Comment by audip** [comment]
Created PR #282 to add dockerfile based on @yannart 's `docker-cerebro` project

**Comment by moliware** [comment]
@yannart thank you very much for the work. We just merged @audip PR (#282) that adds a dockerfile based on your project (Thanks @audip too).

We will add it to dockerhub soon!
