### ISSUE TITLE
Snapshot - diplay indices

### ISSUE THREAD

**Issue by frenkye** [lmenezes/cerebro#89]
Hi,

cerebro-0.5.1 & elastic 5.2.2

in menu more -> snapshot.

Indices (defaults to all if none is selected) doesn't work. It always show all indices tested Chrome / FireFox.

After checking page code I noticed element doesn't change value:
1) Checked
```
<input type="checkbox" ng-model="showSpecialIndices" ng-true-value="true" class="ng-valid ng-dirty ng-valid-parse ng-touched ng-not-empty">
```

2) Empty
```
<input type="checkbox" ng-model="showSpecialIndices" ng-true-value="true" class="ng-valid ng-dirty ng-valid-parse ng-touched ng-empty">
```
Where "ng-true-value" is always true.

![snimek obrazovky 2017-03-08 v 16 40 59](https://cloud.githubusercontent.com/assets/13994937/23710740/0e7b56ec-041e-11e7-90f6-81b56c610bea.png)

PS: Keep up great work!

**Comment by lmenezes** [comment]
@frenkye thanks for reporting! I have been limited on time, but hopefully during the weekend I can close a few issues :)
