### ISSUE TITLE
configuration not read

### ISSUE THREAD

**Issue by elppc** [lmenezes/cerebro#9]
Hi,
Using cluster settings in cerebro, I can't see any value in fields

**Comment by lmenezes** [comment]
hey @elppc 

the ES API used to not load the default values for these settings(this changed in 5.0: https://github.com/elastic/elasticsearch/issues/18645), so for older ES versions this page will only display explicitly set values.

I still have to add that option here, so I will keep the issue open as a reminder. 
thanks for reporting :)

**Comment by lmenezes** [comment]
this is now working as you expect since https://github.com/lmenezes/cerebro/commit/d013025c3a06933e20bece6a4a89d2be7a545903
