### ISSUE TITLE
click "show only unhealthy indices" invalid

### ISSUE THREAD

**Issue by chinatree** [lmenezes/cerebro#90]
Environment:
cerebro-0.5.1
es 2.4.0

Question:
When my cluster is relocating shards, click "show only unhealthy indices" in order to see which index which shard in relocating. But the result is nothing to display. I confirm the shards is still relocating, because one shard have ten gigabyte, relocate it didn't completed so fast, so is not refresh issue.

Using kopf can be normal.

![image](https://cloud.githubusercontent.com/assets/1692877/23740947/e6a62016-04e0-11e7-9535-552aef028a3e.png)

I use chrome(56.0.2924.87 64 bit) or safari(10.0.3) on my mac(10.12.3).

**Comment by lmenezes** [comment]
@chinatree Thank you for reporting! I have also noticed this problem. I will fix it and have a new version released this weekend!
